export interface CityData {
  slug: string;
  name: string;
  nameDE: string;
  country: 'DE' | 'AT' | 'CH';
  district?: string;
  distance_km: number;
  drive_minutes: number;
  population: number;
  population_year: number;
  population_growth: string; // e.g. "+2.3% (2015–2023)"
  area_km2: number;
  elevation_m: number;
  founded?: string;
  description: string;
  history: string;
  sights: string[];
  known_for: string;
  kombi_price: number;
  van_price: number;
}

// Prices from DB: Kombi = 8.00 + 2.10×km, Van = 10.00 + 2.20×km
const calcPrice = (km: number) => ({
  kombi_price: Math.round((8 + 2.1 * km) * 10) / 10,
  van_price: Math.round((10 + 2.2 * km) * 10) / 10,
});

const cities: CityData[] = [
  // ─── GERMANY (Bavaria) ─────────────────────────────────────────────────────
  {
    slug: 'taxi-dachau-flughafen-muenchen',
    name: 'Dachau',
    nameDE: 'Dachau',
    country: 'DE',
    district: 'Landkreis Dachau',
    distance_km: 32,
    drive_minutes: 28,
    population: 48250,
    population_year: 2023,
    population_growth: '+8,4 % (2013–2023)',
    area_km2: 53.4,
    elevation_m: 508,
    founded: 'um 800 n. Chr.',
    description:
      'Dachau ist eine Große Kreisstadt im Landkreis Dachau, nordwestlich von München gelegen und Teil der Metropolregion München.',
    history:
      'Dachau wurde im Mittelalter als Marktsiedlung gegründet und war bis ins 19. Jahrhundert vor allem für seine Papiermühlen und später für die Dachauer Malerschule bekannt, die viele Impressionisten anzog. Im 20. Jahrhundert wurde der Name Dachau weltweit bekannt durch das erste nationalsozialistische Konzentrationslager, das 1933 auf dem Gelände einer ehemaligen Munitionsfabrik errichtet wurde. Heute ist Dachau eine moderne Wohnstadt mit lebendiger Kunstszene und wächst als Teil des Münchner Speckgürtels kontinuierlich.',
    sights: [
      'KZ-Gedenkstätte Dachau',
      'Schloss Dachau & Hofgarten',
      'Gemäldegalerie im Lehnbachhaus (Zweigstelle)',
      'Altstadt Dachau mit Malerviertel',
      'Rathaus und Pfarrkirche St. Jakob',
    ],
    known_for: 'Künstlerkolonie, KZ-Gedenkstätte, Münchner Umland',
    ...calcPrice(32),
  },
  {
    slug: 'taxi-augsburg-flughafen-muenchen',
    name: 'Augsburg',
    nameDE: 'Augsburg',
    country: 'DE',
    district: 'kreisfreie Stadt',
    distance_km: 75,
    drive_minutes: 52,
    population: 299600,
    population_year: 2023,
    population_growth: '+4,1 % (2013–2023)',
    area_km2: 146.9,
    elevation_m: 494,
    founded: '15 v. Chr.',
    description:
      'Augsburg ist die drittgrößte Stadt Bayerns und eine der ältesten Städte Deutschlands, gegründet von den Römern als Augusta Vindelicum.',
    history:
      'Als römische Provinzhauptstadt und bedeutende Handelsmetropole im Mittelalter war Augsburg Sitz der Bankiersfamilien Fugger und Welser, die den Welthandel prägten. Der Augsburger Religionsfrieden von 1555 beendete den ersten Glaubenskrieg in Europa. Heute beheimatet Augsburg wichtige Industrieunternehmen wie MAN, Kuka und Premium Aerotec sowie eine bedeutende Universität.',
    sights: [
      'Augsburger Dom (Hoher Dom Mariä Heimsuchung)',
      'Fuggerei – älteste Sozialsiedlung der Welt',
      'Goldener Saal im Rathaus',
      'Schaezlerpalais & Staatsgalerie',
      'Rotes Tor und historische Stadtmauer',
    ],
    known_for: 'Fugger, Römische Geschichte, UNESCO Wassermanagement-System',
    ...calcPrice(75),
  },
  {
    slug: 'taxi-ingolstadt-flughafen-muenchen',
    name: 'Ingolstadt',
    nameDE: 'Ingolstadt',
    country: 'DE',
    district: 'kreisfreie Stadt',
    distance_km: 82,
    drive_minutes: 55,
    population: 138000,
    population_year: 2023,
    population_growth: '+5,7 % (2013–2023)',
    area_km2: 133.4,
    elevation_m: 365,
    founded: '806 n. Chr.',
    description:
      'Ingolstadt ist die viertgrößte Stadt Bayerns, bekannt als Sitz von Audi und als historische Festungsstadt an der Donau.',
    history:
      'Ingolstadt war Residenzstadt der Wittelsbacher Herzöge und beherbergte ab 1472 die erste Universität Bayerns. Die massiven Befestigungsanlagen aus dem 19. Jahrhundert (Festung Ingolstadt) sind noch heute teilweise erhalten. Im Jahr 1800 wurde in der Stadtmauer der Roman „Frankenstein" von Mary Shelley angeregt – der Anatom Johann Konrad Dippel experimentierte hier. Heute prägt Audi die Stadt als größter Arbeitgeber.',
    sights: [
      'Audi Museum Mobile',
      'Bayerisches Armeemuseum im Neuen Schloss',
      'Liebfrauenmünster',
      'Festungsanlage mit Reduit Tilly',
      'Klenzepark an der Donau',
    ],
    known_for: 'Audi Hauptwerk, Universitätsstadt, Donaufestung',
    ...calcPrice(82),
  },
  {
    slug: 'taxi-rosenheim-flughafen-muenchen',
    name: 'Rosenheim',
    nameDE: 'Rosenheim',
    country: 'DE',
    district: 'kreisfreie Stadt',
    distance_km: 63,
    drive_minutes: 45,
    population: 64600,
    population_year: 2023,
    population_growth: '+6,2 % (2013–2023)',
    area_km2: 38.0,
    elevation_m: 452,
    founded: 'um 1200 n. Chr.',
    description:
      'Rosenheim ist eine kreisfreie Stadt in Oberbayern, gelegen am Inn zwischen München und den Alpen, bedeutendes Einkaufs- und Industriezentrum der Region.',
    history:
      'Rosenheim entstand als Salzumschlagsplatz am Inn im Mittelalter und erhielt 1328 das Stadtrecht. Salz- und Holzhandel machten die Stadt wohlhabend. Im 19. Jahrhundert verband die Eisenbahn Rosenheim mit München und dem Brenner, was die industrielle Entwicklung förderte. Heute ist Rosenheim bekannt für die Glasbranche und Holzverarbeitung sowie als Tor zu den bayerischen Alpen.',
    sights: [
      'Stadtmuseum Rosenheim',
      'Mangfallpark und Inn-Ufer',
      'Max-Josefs-Platz mit historischen Laubengängen',
      'Kunstmuseum Rosenheim',
      'Wendelstein (Ausflugsziel, 47 km)',
    ],
    known_for: 'Inntal, Alpenzugang, Glasindustrie',
    ...calcPrice(63),
  },
  {
    slug: 'taxi-freising-flughafen-muenchen',
    name: 'Freising',
    nameDE: 'Freising',
    country: 'DE',
    district: 'Landkreis Freising',
    distance_km: 7,
    drive_minutes: 10,
    population: 51000,
    population_year: 2023,
    population_growth: '+10,1 % (2013–2023)',
    area_km2: 110.3,
    elevation_m: 448,
    founded: '724 n. Chr.',
    description:
      'Freising liegt direkt neben dem Flughafen München und ist eine der ältesten Bischofsstädte Bayerns mit über 1.300 Jahren Geschichte.',
    history:
      'Freising war jahrhundertelang das geistliche und kulturelle Zentrum Bayerns, noch vor München. Der Domhügel mit Dom und Diözesanmuseum zählt zu den bedeutendsten mittelalterlichen Ensembles Süddeutschlands. Die Weihenstephaner Brauerei (gegründet 1040) gilt als älteste Brauerei der Welt. Papst Benedikt XVI. (Joseph Ratzinger) wurde in Freising zum Priester geweiht.',
    sights: [
      'Freisinger Dom (Dom St. Maria und St. Korbinian)',
      'Diözesanmuseum Freising',
      'Benediktushöhe Weihenstephan – älteste Brauerei der Welt',
      'Altstadt mit Marienplatz',
      'Domberg-Aussichtsterrasse',
    ],
    known_for: 'Domhügel, älteste Brauerei der Welt, Flughafen-Nähe',
    ...calcPrice(7),
  },
  {
    slug: 'taxi-landsberg-am-lech-flughafen-muenchen',
    name: 'Landsberg am Lech',
    nameDE: 'Landsberg am Lech',
    country: 'DE',
    district: 'Landkreis Landsberg am Lech',
    distance_km: 55,
    drive_minutes: 42,
    population: 31800,
    population_year: 2023,
    population_growth: '+7,3 % (2013–2023)',
    area_km2: 66.3,
    elevation_m: 571,
    founded: 'um 1150 n. Chr.',
    description:
      'Landsberg am Lech ist eine malerische Kleinstadt an der Romantischen Straße, bekannt für ihre barocke Altstadt und die prächtige Stadtmauer.',
    history:
      'Herzog Heinrich der Löwe gründete Landsberg im 12. Jahrhundert als Zollstation am Lech. Die Stadt erblühte im Mittelalter dank des Salzhandels. Im 15. Jahrhundert entstand die bis heute erhaltene Stadtmauer. Adolf Hitler schrieb hier während seiner Haft 1923/24 „Mein Kampf" – eine dunkle Episode, mit der die Stadt heute kritisch umgeht.',
    sights: [
      'Stadtmauer und Bayertor',
      'Hauptplatz mit historischen Bürgerhäusern',
      'Johanniskirche',
      'Lechwehr und Lechufer-Promenade',
      'Stadtmuseum Landsberg',
    ],
    known_for: 'Romantische Straße, Bayertor, Lechufer',
    ...calcPrice(55),
  },
  {
    slug: 'taxi-erding-flughafen-muenchen',
    name: 'Erding',
    nameDE: 'Erding',
    country: 'DE',
    district: 'Landkreis Erding',
    distance_km: 18,
    drive_minutes: 18,
    population: 38500,
    population_year: 2023,
    population_growth: '+12,5 % (2013–2023)',
    area_km2: 91.0,
    elevation_m: 459,
    founded: 'um 900 n. Chr.',
    description:
      'Erding liegt östlich des Flughafens München und ist bekannt für seine Therme, das Weißbier und als schnell wachsende Kreisstadt im Münchner Umland.',
    history:
      'Erding erhielt im 14. Jahrhundert das Stadtrecht und war eine wichtige Station auf der Salzstraße von Salzburg nach Augsburg. Im 20. Jahrhundert wurde die Stadt durch den nahegelegenen Flughafen München stark geprägt, der seit 1992 betrieben wird. Erding ist heute eine der am schnellsten wachsenden Städte Bayerns.',
    sights: [
      'Therme Erding – größte Therme Deutschlands',
      'Altstadt mit Schöner Turm',
      'Frauenkirche Erding',
      'Erdinger Weißbräu (Brauerei)',
      'Lengdorfer Weiher (Badesee)',
    ],
    known_for: 'Therme Erding, Erdinger Weißbier, Flughafen-Nähe',
    ...calcPrice(18),
  },
  {
    slug: 'taxi-ebersberg-flughafen-muenchen',
    name: 'Ebersberg',
    nameDE: 'Ebersberg',
    country: 'DE',
    district: 'Landkreis Ebersberg',
    distance_km: 30,
    drive_minutes: 28,
    population: 12800,
    population_year: 2023,
    population_growth: '+9,2 % (2013–2023)',
    area_km2: 38.2,
    elevation_m: 556,
    founded: 'um 1000 n. Chr.',
    description:
      'Ebersberg ist eine Kreisstadt östlich von München, Tor zum Ebersberger Forst – dem größten zusammenhängenden Waldgebiet Bayerns.',
    history:
      'Ein Benediktinerkloster (924 gegründet) war der Ursprung der Siedlung. Im 19. Jahrhundert erhielt Ebersberg Stadtrecht und Eisenbahnanschluss. Das Kloster wurde säkularisiert, die romanische Klosterkirche ist jedoch erhalten. Der umliegende Ebersberger Forst mit 10.000 Hektar ist ein bedeutendes Naherholungsgebiet.',
    sights: [
      'Klosterkirche St. Sebastian',
      'Ebersberger Forst – größter Wald Bayerns',
      'Altes Rathaus',
      'Stadtmuseum Ebersberg',
      'Grafinger See (Naherholung)',
    ],
    known_for: 'Ebersberger Forst, Klosterkirche, Münchner Umland',
    ...calcPrice(30),
  },
  {
    slug: 'taxi-starnberg-flughafen-muenchen',
    name: 'Starnberg',
    nameDE: 'Starnberg',
    country: 'DE',
    district: 'Landkreis Starnberg',
    distance_km: 35,
    drive_minutes: 35,
    population: 23900,
    population_year: 2023,
    population_growth: '+6,8 % (2013–2023)',
    area_km2: 34.9,
    elevation_m: 584,
    founded: 'um 1200 n. Chr.',
    description:
      'Starnberg liegt am nördlichen Ufer des Starnberger Sees, einem der bekanntesten bayerischen Seen, und gilt als exklusiver Wohnort im Münchner Umland.',
    history:
      'Starnberg entwickelte sich im 19. Jahrhundert zum beliebten Sommerfrischeort für die Münchner Bevölkerung und den bayerischen Adel. König Ludwig II. ertrank 1886 unter ungeklärten Umständen im Starnberger See – ein bis heute ungelöstes Rätsel der bayerischen Geschichte. Der Landkreis Starnberg zählt zu den wohlhabendsten Deutschlands.',
    sights: [
      'Starnberger See – Bootsfahrten & Strandpromenaden',
      'Votivkapelle zum Gedächtnis König Ludwigs II.',
      'Schloss Berg (Privatbesitz, Außenansicht)',
      'Museum Starnberger See',
      'Segelregatten im Sommer',
    ],
    known_for: 'Starnberger See, König Ludwig II., Alpen-Panorama',
    ...calcPrice(35),
  },
  {
    slug: 'taxi-wolfratshausen-flughafen-muenchen',
    name: 'Wolfratshausen',
    nameDE: 'Wolfratshausen',
    country: 'DE',
    district: 'Landkreis Bad Tölz-Wolfratshausen',
    distance_km: 38,
    drive_minutes: 35,
    population: 18700,
    population_year: 2023,
    population_growth: '+5,9 % (2013–2023)',
    area_km2: 40.0,
    elevation_m: 571,
    founded: 'um 1100 n. Chr.',
    description:
      'Wolfratshausen liegt an der Loisach südlich von München und ist Ausgangspunkt für Floßfahrten auf der Isar – ein traditionsreiches Freizeitvergnügen.',
    history:
      'Die Stadt am Zusammenfluss von Loisach und Isar war seit dem Mittelalter ein wichtiger Handelsplatz. Flözer transportierten über Jahrhunderte Holz und Salz von den Alpen nach München. Diese Tradition der Floßfahrten lebt bis heute als touristisches Highlight fort.',
    sights: [
      'Floßlände – Start der legendären Isarl-Floßfahrten',
      'Altstadt mit Marienplatz',
      'Loisachufer-Promenade',
      'Waldmuseum Wolfratshausen',
      'Kloster Beuerberg (Nähe, 12 km)',
    ],
    known_for: 'Floßfahrten auf der Isar, Loisach, Alpenvorland',
    ...calcPrice(38),
  },
  {
    slug: 'taxi-bad-toelz-flughafen-muenchen',
    name: 'Bad Tölz',
    nameDE: 'Bad Tölz',
    country: 'DE',
    district: 'Landkreis Bad Tölz-Wolfratshausen',
    distance_km: 52,
    drive_minutes: 45,
    population: 19200,
    population_year: 2023,
    population_growth: '+4,5 % (2013–2023)',
    area_km2: 63.4,
    elevation_m: 670,
    founded: 'um 1000 n. Chr.',
    description:
      'Bad Tölz ist ein bekannter Kurort an der Isar mit einer der schönsten Altstädte Bayerns und traditionellem Trachten- und Schützenwesen.',
    history:
      'Bad Tölz war im Mittelalter ein wichtiger Handelsort auf der Salzstraße. Ab dem 19. Jahrhundert entwickelte es sich zum Kurbad dank der jodhaltigen Quellen. Die malerische Altstadt mit den bunt bemalten Bürgerhäusern am Marktstrasse prägt das Stadtbild bis heute. Das Leonhardifahrt-Fest im November ist eine der bekanntesten Prozessionen Bayerns.',
    sights: [
      'Marktstraße mit historischen Lüftlmalereien',
      'Kalvarienberg mit Heilig-Kreuz-Kirche',
      'Alpamare Thermen- und Freizeitbad',
      'Stadtmuseum Bad Tölz',
      'Blomberg (Sommerrodelbahn & Wandergebiet)',
    ],
    known_for: 'Kurort, Jod-Quellen, Leonhardifahrt',
    ...calcPrice(52),
  },
  {
    slug: 'taxi-miesbach-flughafen-muenchen',
    name: 'Miesbach',
    nameDE: 'Miesbach',
    country: 'DE',
    district: 'Landkreis Miesbach',
    distance_km: 48,
    drive_minutes: 42,
    population: 11900,
    population_year: 2023,
    population_growth: '+6,7 % (2013–2023)',
    area_km2: 42.8,
    elevation_m: 690,
    founded: 'um 1100 n. Chr.',
    description:
      'Miesbach ist die Kreisstadt des gleichnamigen Landkreises im oberbayerischen Alpenvorland, bekannt als Ausgangspunkt für Ausflüge in die Bayerischen Alpen.',
    history:
      'Miesbach erhielt im 13. Jahrhundert Marktrecht und war ein wichtiger Handelsplatz auf dem Weg nach Salzburg. Die Brauerei tradition ist tief verwurzelt – das Miesbacher Bier wurde bis ins 19. Jahrhundert weit gehandelt. Der Landkreis Miesbach gehört zu den landschaftlich schönsten und wirtschaftlich stärksten Regionen Bayerns.',
    sights: [
      'Stadtpfarrkirche Mariä Himmelfahrt',
      'Schlossanger Alp (Wandern & Skifahren)',
      'Wendelstein (1.838 m, Seilbahn)',
      'Schliersee (nahe, 12 km)',
      'Tegernsee (nahe, 18 km)',
    ],
    known_for: 'Alpenvorland, Tegernsee-Schliersee-Region, Bergpanorama',
    ...calcPrice(48),
  },
  {
    slug: 'taxi-weilheim-flughafen-muenchen',
    name: 'Weilheim in Oberbayern',
    nameDE: 'Weilheim i.OB',
    country: 'DE',
    district: 'Landkreis Weilheim-Schongau',
    distance_km: 58,
    drive_minutes: 48,
    population: 23100,
    population_year: 2023,
    population_growth: '+5,2 % (2013–2023)',
    area_km2: 49.4,
    elevation_m: 599,
    founded: 'um 1100 n. Chr.',
    description:
      'Weilheim in Oberbayern ist eine Kleinstadt südlich von München im Voralpenland, Einkaufszentrum der Region zwischen Ammersee und den Alpen.',
    history:
      'Weilheim erhielt 1330 das Stadtrecht und war ein bedeutender Marktort in der Region. Die Stadt liegt nahe mehrerer Seen (Ammersee, Starnberger See, Staffelsee) und ist damit ein beliebter Ausgangspunkt für Natur- und Wassersportaktivitäten. Die historische Altstadt mit dem Stadtturm ist gut erhalten.',
    sights: [
      'Stadtpfarrkirche Mariä Himmelfahrt',
      'Stadtturm und historischer Marktplatz',
      'Ammersee (15 km)',
      'Staffelsee (20 km)',
      'Wessobrunn (Kloster, 12 km)',
    ],
    known_for: 'Voralpenland, Seenlandschaft, historische Altstadt',
    ...calcPrice(58),
  },
  {
    slug: 'taxi-schongau-flughafen-muenchen',
    name: 'Schongau',
    nameDE: 'Schongau',
    country: 'DE',
    district: 'Landkreis Weilheim-Schongau',
    distance_km: 68,
    drive_minutes: 55,
    population: 12200,
    population_year: 2023,
    population_growth: '+3,8 % (2013–2023)',
    area_km2: 31.7,
    elevation_m: 703,
    founded: 'um 1100 n. Chr.',
    description:
      'Schongau ist eine historische Lechstadt auf einem Hochplateau über dem Lech, Teil der Romantischen Straße mit fast vollständig erhaltener Stadtmauer.',
    history:
      'Schongau war im Mittelalter ein wichtiger Handels- und Umschlagsplatz am Lech. Die fast vollständig erhaltene Stadtmauer aus dem 14. Jahrhundert ist das bedeutendste Baudenkmal der Stadt. Das Ballenhaus, eines der ältesten Handelshäuser Bayerns, zeugt von der wirtschaftlichen Bedeutung im Mittelalter.',
    sights: [
      'Mittelalterliche Stadtmauer (fast vollständig erhalten)',
      'Ballenhaus (15. Jh.)',
      'Stadtpfarrkirche Mariä Himmelfahrt',
      'Lechufer und Lech-Schlucht',
      'Romantische Straße Radweg',
    ],
    known_for: 'Romantische Straße, mittelalterliche Stadtmauer, Lechtal',
    ...calcPrice(68),
  },
  {
    slug: 'taxi-fuerstenfeldbruck-flughafen-muenchen',
    name: 'Fürstenfeldbruck',
    nameDE: 'Fürstenfeldbruck',
    country: 'DE',
    district: 'Landkreis Fürstenfeldbruck',
    distance_km: 30,
    drive_minutes: 28,
    population: 38600,
    population_year: 2023,
    population_growth: '+7,9 % (2013–2023)',
    area_km2: 34.7,
    elevation_m: 516,
    founded: 'um 1250 n. Chr.',
    description:
      'Fürstenfeldbruck ist eine westlich von München gelegene Stadt, bekannt für das ehemalige Zisterzienserkloster Fürstenfeld und als Teil des Münchner Speckgürtels.',
    history:
      'Das Kloster Fürstenfeld wurde 1263 von Herzog Ludwig II. als Sühne für die Ermordung seiner Frau Maria von Brabant gegründet. Die Klosterkirche ist ein Hauptwerk des süddeutschen Barocks. Der Ort wurde durch die Olympischen Spiele 1972 weltweit bekannt, als auf dem ehemaligen Fliegerhorst das Attentat auf die israelische Mannschaft seinen tragischen Ausgang nahm.',
    sights: [
      'Kloster Fürstenfeld (Barockkirche)',
      'Amper-Ufer Spazierwege',
      'Stadtmuseum Fürstenfeldbruck',
      'Fliegerhorst (ehem. Militärflugplatz, jetzt Stadtentwicklung)',
      'Bruck – Altstadt am Amperufer',
    ],
    known_for: 'Kloster Fürstenfeld, Olympia 1972, Ampertal',
    ...calcPrice(30),
  },
  {
    slug: 'taxi-germering-flughafen-muenchen',
    name: 'Germering',
    nameDE: 'Germering',
    country: 'DE',
    district: 'Landkreis Fürstenfeldbruck',
    distance_km: 24,
    drive_minutes: 24,
    population: 40600,
    population_year: 2023,
    population_growth: '+9,6 % (2013–2023)',
    area_km2: 19.5,
    elevation_m: 527,
    description:
      'Germering ist die größte Stadt im Landkreis Fürstenfeldbruck, westlich von München gelegen, und zählt zu den am stärksten wachsenden Kommunen Bayerns.',
    history:
      'Germering entstand im 20. Jahrhundert durch das Zusammenwachsen mehrerer Ortschaften und erlebte nach dem Zweiten Weltkrieg durch den Zuzug von Heimatvertriebenen und Münchner Pendlern ein enormes Wachstum. Heute ist Germering eine moderne Wohnstadt mit guter Infrastruktur und S-Bahn-Anbindung nach München.',
    sights: [
      'Germering-See (Naherholung)',
      'Stadtpark Germering',
      'St.-Jakobus-Kirche',
      'Wildpark Pasing (10 km)',
      'Ammersee (20 km)',
    ],
    known_for: 'Münchner Speckgürtel, Wachstumskommune, S-Bahn-Nähe',
    ...calcPrice(24),
  },
  {
    slug: 'taxi-gauting-flughafen-muenchen',
    name: 'Gauting',
    nameDE: 'Gauting',
    country: 'DE',
    district: 'Landkreis Starnberg',
    distance_km: 25,
    drive_minutes: 25,
    population: 19500,
    population_year: 2023,
    population_growth: '+5,1 % (2013–2023)',
    area_km2: 66.7,
    elevation_m: 564,
    description:
      'Gauting ist eine wohlhabende Gemeinde im Landkreis Starnberg südwestlich von München, beliebt bei Pendlern und bekannt für Künstler und Intellektuelle.',
    history:
      'Gauting wurde im Mittelalter als Bauerndorf erstmals urkundlich erwähnt und entwickelte sich im 19. Jahrhundert durch die Eisenbahn zum bevorzugten Wohnort für Münchner Bürger. Bekannte Persönlichkeiten wie Josef von Sternberg (Filmregisseur) lebten hier. Der Ortsteil Buchendorf ist ein beliebtes Ausflugsziel am Würmtal.',
    sights: [
      'Christuskirche Gauting (Architektur)',
      'Würmufer-Spazierwege',
      'Starnberger See (10 km)',
      'Buchendorf im Würmtal',
      'Ammersee (25 km)',
    ],
    known_for: 'Würmtal, Starnberger-See-Nähe, Münchner Villenviertel',
    ...calcPrice(25),
  },
  {
    slug: 'taxi-puchheim-flughafen-muenchen',
    name: 'Puchheim',
    nameDE: 'Puchheim',
    country: 'DE',
    district: 'Landkreis Fürstenfeldbruck',
    distance_km: 22,
    drive_minutes: 22,
    population: 22000,
    population_year: 2023,
    population_growth: '+8,4 % (2013–2023)',
    area_km2: 12.5,
    elevation_m: 520,
    description:
      'Puchheim ist eine Gemeinde westlich von München im Landkreis Fürstenfeldbruck, stark durch Münchner Pendler geprägt und S-Bahn-erschlossen.',
    history:
      'Puchheim war bis ins 20. Jahrhundert ein kleines Bauerndorf. Durch den Bau der S-Bahn-Linie S4 und die Nähe zu München entwickelte sich der Ort zur Wohngemeinde für Münchner Pendler. Heute besteht Puchheim aus den Ortsteilen Puchheim-Bahnhof und Puchheim-Ort.',
    sights: [
      'Puchheimer Weiher (Naherholung)',
      'Altort Puchheim (historisches Ortszentrum)',
      'Germering-See (5 km)',
      'Kloster Fürstenfeldbruck (8 km)',
      'Ammersee (22 km)',
    ],
    known_for: 'S-Bahn-Gemeinde, Münchner Pendler, Westliches Umland',
    ...calcPrice(22),
  },
  {
    slug: 'taxi-unterschleissheim-flughafen-muenchen',
    name: 'Unterschleißheim',
    nameDE: 'Unterschleißheim',
    country: 'DE',
    district: 'Landkreis München',
    distance_km: 18,
    drive_minutes: 18,
    population: 28400,
    population_year: 2023,
    population_growth: '+10,8 % (2013–2023)',
    area_km2: 26.3,
    elevation_m: 482,
    description:
      'Unterschleißheim liegt nördlich von München direkt an der A9, bekannt als Sitz von BMW Group Fahrzeugtechnik und als schnell wachsende Gemeinde.',
    history:
      'Unterschleißheim war bis in die 1960er Jahre ein kleines Dorf. Durch die Ansiedlung von Industrie und BMW sowie den Bau neuer Wohngebiete wuchs die Gemeinde explosiv. Heute ist Unterschleißheim ein wichtiger Wirtschaftsstandort im Norden Münchens mit ausgezeichneter Infrastruktur.',
    sights: [
      'Baggersee Unterschleißheim (Badesee)',
      'BMW Group Testgelände',
      'Siedlungskirche Heilig Kreuz',
      'Schloss Unterschleißheim',
      'Flughafen München (10 km)',
    ],
    known_for: 'BMW Nähe, Nördliches München, Baggersee',
    ...calcPrice(18),
  },
  {
    slug: 'taxi-garching-flughafen-muenchen',
    name: 'Garching bei München',
    nameDE: 'Garching b. München',
    country: 'DE',
    district: 'Landkreis München',
    distance_km: 22,
    drive_minutes: 20,
    population: 18200,
    population_year: 2023,
    population_growth: '+13,2 % (2013–2023)',
    area_km2: 28.0,
    elevation_m: 482,
    description:
      'Garching bei München ist ein Wissenschaftsstandort mit Forschungsreaktor, TU-München-Campus und mehreren Max-Planck-Instituten nordöstlich von München.',
    history:
      'Garching war bis in die 1950er Jahre ein Bauerndorf. Mit der Ansiedlung des Forschungsreaktors der TU München (1957) und zahlreicher Forschungseinrichtungen wurde Garching zu einem weltweit bekannten Wissenschaftszentrum. Heute forschen hier über 20.000 Wissenschaftler und Studenten.',
    sights: [
      'Forschungsreaktor München II (Besichtigungen)',
      'TU München Campus Garching',
      'Hochbrück U-Bahn-Endstation (Design)',
      'Isartal (Naherholung)',
      'Olympiapark München (20 km)',
    ],
    known_for: 'TU München, Forschungszentrum, Wissenschaftsstadt',
    ...calcPrice(22),
  },
  {
    slug: 'taxi-ismaning-flughafen-muenchen',
    name: 'Ismaning',
    nameDE: 'Ismaning',
    country: 'DE',
    district: 'Landkreis München',
    distance_km: 20,
    drive_minutes: 20,
    population: 15800,
    population_year: 2023,
    population_growth: '+8,9 % (2013–2023)',
    area_km2: 36.9,
    elevation_m: 492,
    description:
      'Ismaning liegt nordöstlich von München und ist bekannt als Sitz mehrerer Medienunternehmen, insbesondere des BR (Bayerischer Rundfunk).',
    history:
      'Ismaning hat eine über 1.000-jährige Geschichte. Das Schloss Ismaning war Sommerresidenz der Münchner Fürstbischöfe. Im 20. Jahrhundert siedelten sich hier viele Medienunternehmen an. Die Ismaning-Fischteiche sind ein bedeutendes Vogelschutzgebiet.',
    sights: [
      'Schloss Ismaning (Stadtmuseum)',
      'Ismaning-Fischteiche (Naturschutzgebiet)',
      'Bayerischer Rundfunk (BR) Hauptsitz',
      'Schlossgarten Ismaning',
      'Isartal (Naherholung)',
    ],
    known_for: 'Medienstandort, Schloss Ismaning, Fischteiche',
    ...calcPrice(20),
  },
  {
    slug: 'taxi-vaterstetten-flughafen-muenchen',
    name: 'Vaterstetten',
    nameDE: 'Vaterstetten',
    country: 'DE',
    district: 'Landkreis Ebersberg',
    distance_km: 25,
    drive_minutes: 25,
    population: 24100,
    population_year: 2023,
    population_growth: '+7,6 % (2013–2023)',
    area_km2: 27.4,
    elevation_m: 524,
    description:
      'Vaterstetten ist eine der größten Gemeinden des Landkreises Ebersberg im östlichen Münchner Umland, eine typische S-Bahn-Pendlergemeinde.',
    history:
      'Vaterstetten entstand im 20. Jahrhundert durch den Zusammenschluss mehrerer Dörfer. Der Ort wuchs nach dem Zweiten Weltkrieg durch den Zuzug von Heimatvertriebenen rasant. Heute ist Vaterstetten eine moderne Wohngemeinde mit direkter S-Bahn-Verbindung nach München.',
    sights: [
      'Waldgebiete im Ebersberger Forst (Nähe)',
      'Schönau am Ebersberger Forst',
      'Parksee Vaterstetten',
      'Pfarrkirche Heilig Kreuz',
      'Ebersberg (10 km)',
    ],
    known_for: 'Münchner Ostumland, S-Bahn-Gemeinde, Ebersberger Forst',
    ...calcPrice(25),
  },
  {
    slug: 'taxi-gilching-flughafen-muenchen',
    name: 'Gilching',
    nameDE: 'Gilching',
    country: 'DE',
    district: 'Landkreis Starnberg',
    distance_km: 28,
    drive_minutes: 28,
    population: 17800,
    population_year: 2023,
    population_growth: '+9,1 % (2013–2023)',
    area_km2: 41.7,
    elevation_m: 570,
    description:
      'Gilching ist eine Gemeinde im Landkreis Starnberg, bekannt als Sitz der Firma Webasto und als grüne Wohngemeinde im Würmtal.',
    history:
      'Gilching war ein kleines Bauerndorf, das sich im 20. Jahrhundert zur Wohngemeinde für Münchner entwickelte. Die Firma Webasto (Automobilzulieferer) hat hier ihren Hauptsitz und ist der größte Arbeitgeber der Region. Der Ammersee und Starnberger See sind von Gilching gut erreichbar.',
    sights: [
      'Ammersee (15 km)',
      'Starnberger See (18 km)',
      'Würmtal Radweg',
      'Webasto Firmensitz (Wirtschaft)',
      'Seefeld am Pilsensee (10 km)',
    ],
    known_for: 'Webasto, Würmtal, Seenlandschaft',
    ...calcPrice(28),
  },
  {
    slug: 'taxi-olching-flughafen-muenchen',
    name: 'Olching',
    nameDE: 'Olching',
    country: 'DE',
    district: 'Landkreis Fürstenfeldbruck',
    distance_km: 26,
    drive_minutes: 26,
    population: 27900,
    population_year: 2023,
    population_growth: '+10,2 % (2013–2023)',
    area_km2: 20.3,
    elevation_m: 505,
    description:
      'Olching liegt im Ampertal westlich von München und ist eine der wachstumsstärksten Gemeinden im Landkreis Fürstenfeldbruck.',
    history:
      'Olching hat eine frühmittelalterliche Geschichte und wurde durch die Eisenbahn und später durch die S-Bahn zur Wohngemeinde für Münchner Pendler. Die Amper und umliegende Auwälder sind wichtige Naherholungsgebiete.',
    sights: [
      'Amper-Auwälder (Naturschutz)',
      'Olchinger See (Badesee)',
      'Stadtmuseum Olching',
      'Kloster Fürstenfeldbruck (8 km)',
      'Gernlinden Moor (Naturschutz)',
    ],
    known_for: 'Ampertal, Wachstumskommune, S-Bahn westlich München',
    ...calcPrice(26),
  },
  {
    slug: 'taxi-grafing-flughafen-muenchen',
    name: 'Grafing bei München',
    nameDE: 'Grafing b. München',
    country: 'DE',
    district: 'Landkreis Ebersberg',
    distance_km: 34,
    drive_minutes: 30,
    population: 14200,
    population_year: 2023,
    population_growth: '+8,3 % (2013–2023)',
    area_km2: 34.7,
    elevation_m: 530,
    description:
      'Grafing bei München ist eine Kleinstadt im Landkreis Ebersberg östlich von München mit historischer Altstadt und S-Bahn-Anschluss.',
    history:
      'Grafing erhielt im 14. Jahrhundert das Stadtrecht und war ein wichtiger Marktort auf dem Weg nach Salzburg. Die gut erhaltene Altstadt mit Stadtturm und historischen Häusern ist ein Wahrzeichen der Stadt. Im 19. Jahrhundert kamen Industrie und Eisenbahn.',
    sights: [
      'Stadtturm Grafing',
      'Historische Altstadt',
      'Grafinger See (Badesee)',
      'Pfarrkirche St. Ägidius',
      'Ebersberger Forst (10 km)',
    ],
    known_for: 'Historische Altstadt, Grafinger See, östliches München-Umland',
    ...calcPrice(34),
  },
  {
    slug: 'taxi-kirchheim-bei-muenchen-flughafen-muenchen',
    name: 'Kirchheim bei München',
    nameDE: 'Kirchheim b. München',
    country: 'DE',
    district: 'Landkreis München',
    distance_km: 20,
    drive_minutes: 20,
    population: 13800,
    population_year: 2023,
    population_growth: '+11,4 % (2013–2023)',
    area_km2: 10.5,
    elevation_m: 492,
    description:
      'Kirchheim bei München liegt unmittelbar östlich der Landeshauptstadt und ist eine der am dichtesten besiedelten und stärksten wachsenden Gemeinden des Landkreises München.',
    history:
      'Kirchheim wurde im 20. Jahrhundert durch Neubausiedlungen stark erweitert. Die günstige Lage nahe der A94 und der direkten S-Bahn-Verbindung nach München macht es beliebt bei Familien und Berufspendlern. Die Messestadt Riem liegt in unmittelbarer Nähe.',
    sights: [
      'Riemer Park (ehem. Expo-Gelände)',
      'Messestadt Riem (10 min)',
      'Heimstettener See (Badesee)',
      'Pfarrkirche St. Nikolaus',
      'Flughafen München (12 km)',
    ],
    known_for: 'Messestadt-Nähe, östliches Münchner Umland, Riemer Park',
    ...calcPrice(20),
  },
  {
    slug: 'taxi-haar-flughafen-muenchen',
    name: 'Haar',
    nameDE: 'Haar',
    country: 'DE',
    district: 'Landkreis München',
    distance_km: 22,
    drive_minutes: 22,
    population: 21400,
    population_year: 2023,
    population_growth: '+9,7 % (2013–2023)',
    area_km2: 14.4,
    elevation_m: 530,
    description:
      'Haar ist eine östliche Münchner Umlandgemeinde, bekannt als Sitz des Isar-Amper-Klinikums und als gut erschlossener Wohnort an der S-Bahn.',
    history:
      'Haar entwickelte sich im 20. Jahrhundert zur Wohngemeinde. Das Isar-Amper-Klinikum (ehem. Heil- und Pflegeanstalt) ist seit über 100 Jahren das prägende Gebäude der Gemeinde. Heute ist Haar dicht bebaut und durch U-Bahn und S-Bahn gut an München angebunden.',
    sights: [
      'Parkanlage des Isar-Amper-Klinikums',
      'Ortszentrum mit Pfarrkirche',
      'Riemer Park (8 km)',
      'Egglburger See (12 km)',
      'München-Ost (15 min S-Bahn)',
    ],
    known_for: 'Klinikstandort, östliches Münchner Umland, S-Bahn-Nähe',
    ...calcPrice(22),
  },
  {
    slug: 'taxi-holzkirchen-flughafen-muenchen',
    name: 'Holzkirchen',
    nameDE: 'Holzkirchen',
    country: 'DE',
    district: 'Landkreis Miesbach',
    distance_km: 35,
    drive_minutes: 32,
    population: 16800,
    population_year: 2023,
    population_growth: '+8,2 % (2013–2023)',
    area_km2: 44.4,
    elevation_m: 682,
    description:
      'Holzkirchen ist eine Marktgemeinde südöstlich von München im Voralpenland und bekannt als Geburtsort des Bierkrugdesigners und für den Holzkirchner Bockbierfest.',
    history:
      'Holzkirchen wurde im 12. Jahrhundert als Markt gegründet und war im Mittelalter ein wichtiger Zwischenstopp auf dem Weg nach Südtirol. Die Brautradition ist tief verwurzelt – das Holzkirchner Brauhaus ist über 500 Jahre alt. Heute ist Holzkirchen ein wirtschaftlich starkes Oberzentrum des Landkreises Miesbach.',
    sights: [
      'Holzkirchner Bockbierfest (jährlich)',
      'Pfarrkirche St. Laurentius',
      'Mangfall-Auen (Naturschutz)',
      'Hausham (Bergbau-Museum, 15 km)',
      'Tegernsee (25 km)',
    ],
    known_for: 'Bockbierfest, Brautradition, Voralpenland',
    ...calcPrice(35),
  },
  {
    slug: 'taxi-tutzing-flughafen-muenchen',
    name: 'Tutzing',
    nameDE: 'Tutzing',
    country: 'DE',
    district: 'Landkreis Starnberg',
    distance_km: 42,
    drive_minutes: 40,
    population: 9800,
    population_year: 2023,
    population_growth: '+4,3 % (2013–2023)',
    area_km2: 42.3,
    elevation_m: 588,
    description:
      'Tutzing am Starnberger See ist eine malerische Gemeinde mit Schloss, bekannt als Veranstaltungsort der Evangelischen Akademie Tutzing und beliebtes Ausflugsziel.',
    history:
      'Das Schloss Tutzing war einst Sommerresidenz des Adels. Im 19. Jahrhundert entdeckten Münchner Bürger Tutzing als Ausflugsziel. Die Evangelische Akademie Tutzing (seit 1947) ist ein bedeutendes Forum für gesellschaftliche und politische Debatten. Am Starnberger See erholten sich viele bekannte Künstler und Musiker.',
    sights: [
      'Schloss Tutzing (Evangelische Akademie)',
      'Starnberger See – Seepromenade',
      'Pfarrkirche St. Joseph',
      'Buchberg bei Tutzing (Aussichtspunkt)',
      'Segelclub Tutzing',
    ],
    known_for: 'Starnberger See, Evangelische Akademie, Seeblick',
    ...calcPrice(42),
  },
  {
    slug: 'taxi-penzberg-flughafen-muenchen',
    name: 'Penzberg',
    nameDE: 'Penzberg',
    country: 'DE',
    district: 'Landkreis Weilheim-Schongau',
    distance_km: 52,
    drive_minutes: 45,
    population: 17200,
    population_year: 2023,
    population_growth: '+5,7 % (2013–2023)',
    area_km2: 37.6,
    elevation_m: 588,
    description:
      'Penzberg ist eine ehemalige Bergbaustadt am Fuß der Bayerischen Alpen, heute bekannt als Standort von Roche (F. Hoffmann-La Roche AG) – einem der größten Pharmaunternehmen Europas.',
    history:
      'Penzberg war über 100 Jahre ein Steinkohlen-Bergbaustandort (1871–1966). Die Geschichte endete mit Schließung der Zeche. Danach diversifizierte sich die Wirtschaft, und Roche baute hier ein großes Produktionszentrum auf. Heute arbeiten über 9.000 Menschen am Roche-Standort Penzberg.',
    sights: [
      'Museum Penzberg (Stadtgeschichte & Bergbau)',
      'Roche-Campusgebäude (Architektur)',
      'Loisach-Ufer',
      'Icking (Isartal, 18 km)',
      'Kochelsee (20 km)',
    ],
    known_for: 'Roche Pharmaunternehmen, Bergbaugeschichte, Alpenvorland',
    ...calcPrice(52),
  },
  {
    slug: 'taxi-murnau-flughafen-muenchen',
    name: 'Murnau am Staffelsee',
    nameDE: 'Murnau a. Staffelsee',
    country: 'DE',
    district: 'Landkreis Garmisch-Partenkirchen',
    distance_km: 72,
    drive_minutes: 58,
    population: 12400,
    population_year: 2023,
    population_growth: '+4,1 % (2013–2023)',
    area_km2: 75.1,
    elevation_m: 698,
    description:
      'Murnau am Staffelsee ist ein traditionsreicher Marktflecken in Oberbayern, bekannt als einstiger Treffpunkt des Blauen Reiter (Kandinsky, Marc) und für seinen Blick auf die Zugspitze.',
    history:
      'Murnau war Anfang des 20. Jahrhunderts ein bedeutender Ort für die Kunstbewegung „Der Blaue Reiter". Wassily Kandinsky und Gabriele Münter lebten hier und schufen einige ihrer bedeutendsten Werke. Der Staffelsee, umgeben von Mooren und Feldern, inspirierte viele Künstler. Heute ist Murnau ein beliebter Kurort und Tourismusdestination.',
    sights: [
      'Schloßmuseum Murnau (Blaue Reiter)',
      'Gabriele Münter Haus',
      'Staffelsee – Badeplätze und Bootsvermietung',
      'Naturschutzgebiet Murnauer Moos',
      'Wettersteingebirge Panorama',
    ],
    known_for: 'Blaue Reiter Kunstbewegung, Staffelsee, Alpenblick',
    ...calcPrice(72),
  },
  {
    slug: 'taxi-garmisch-partenkirchen-flughafen-muenchen',
    name: 'Garmisch-Partenkirchen',
    nameDE: 'Garmisch-Partenkirchen',
    country: 'DE',
    district: 'Landkreis Garmisch-Partenkirchen',
    distance_km: 95,
    drive_minutes: 75,
    population: 27500,
    population_year: 2023,
    population_growth: '+3,2 % (2013–2023)',
    area_km2: 203.8,
    elevation_m: 708,
    founded: 'um 800 n. Chr.',
    description:
      'Garmisch-Partenkirchen ist Deutschlands bekanntester Wintersportort am Fuß der Zugspitze (2.962 m) und Austragungsort der Olympischen Winterspiele 1936.',
    history:
      'Die zwei ehemals getrennten Ortschaften Garmisch und Partenkirchen wurden 1935 zur Doppelstadt vereint. Die Olympischen Winterspiele 1936 hinterließen zahlreiche Sportstätten. Die Zugspitze, Deutschlands höchster Berg, macht die Region zur beliebtesten Wintersportdestination Deutschlands. Der Komponist Richard Strauss lebte und starb hier.',
    sights: [
      'Zugspitze (2.962 m) mit Seilbahn',
      'Partnachklamm',
      'Richard-Strauss-Institut',
      'Olympia-Skistadion',
      'Wank (Bergbahn, Alpenblick)',
    ],
    known_for: 'Zugspitze, Wintersport, Olympia 1936',
    ...calcPrice(95),
  },
  {
    slug: 'taxi-bad-reichenhall-flughafen-muenchen',
    name: 'Bad Reichenhall',
    nameDE: 'Bad Reichenhall',
    country: 'DE',
    district: 'Landkreis Berchtesgadener Land',
    distance_km: 142,
    drive_minutes: 95,
    population: 16100,
    population_year: 2023,
    population_growth: '+2,8 % (2013–2023)',
    area_km2: 109.7,
    elevation_m: 470,
    founded: 'vor 2500 Jahren',
    description:
      'Bad Reichenhall ist ein traditionsreicher Soleheilbad-Kurort im Berchtesgadener Land nahe der österreichischen Grenze, mit hochrangiger Salzgewinnung seit der Antike.',
    history:
      'Salz prägte Bad Reichenhall seit 2.500 Jahren. Die Alten Salines (Gradierwerke) sind als technisches Denkmal erhalten. Bad Reichenhall war im 19. Jahrhundert ein bevorzugter Kurort des europäischen Adels. Königin Marie von Bayern ließ hier 1846 das Gradierwerk errichten. Heute ist die Stadt ein Gesundheitsresort mit Sole-Heilanwendungen.',
    sights: [
      'Alte Saline und Salzmuseum',
      'Gradierwerk (Sole-Inhalation)',
      'Predigtstuhl-Bahn (1.614 m)',
      'Kurgarten und Kurhaus',
      'Stiftskirche St. Zeno',
    ],
    known_for: 'Salzheilbad, Kursaal, Berchtesgadener Land',
    ...calcPrice(142),
  },
  {
    slug: 'taxi-berchtesgaden-flughafen-muenchen',
    name: 'Berchtesgaden',
    nameDE: 'Berchtesgaden',
    country: 'DE',
    district: 'Landkreis Berchtesgadener Land',
    distance_km: 150,
    drive_minutes: 100,
    population: 7600,
    population_year: 2023,
    population_growth: '+2,1 % (2013–2023)',
    area_km2: 165.6,
    elevation_m: 572,
    founded: 'um 1100 n. Chr.',
    description:
      'Berchtesgaden ist eine historische Bergmarktgemeinde im Nationalpark Berchtesgaden, weltbekannt durch den Königssee und die Geschichte des NS-Regimes.',
    history:
      'Das Augustiner-Chorherrenstift Berchtesgaden (gegr. 1102) war jahrhundertelang das politische Zentrum der Region. Im 20. Jahrhundert wurde Berchtesgaden durch den „Berghof" – Hitlers Bergsresidenz auf dem Obersalzberg – international bekannt. Heute ist es ein populäres Touristenziel mit Nationalpark und Königssee.',
    sights: [
      'Königssee mit Bootsfahrten',
      'Salzbergwerk Berchtesgaden',
      'Dokumentation Obersalzberg',
      'Kehlsteinhaus ("Adlerhorst")',
      'Nationalpark Berchtesgaden',
    ],
    known_for: 'Königssee, Nationalpark, Obersalzberg',
    ...calcPrice(150),
  },
  {
    slug: 'taxi-traunstein-flughafen-muenchen',
    name: 'Traunstein',
    nameDE: 'Traunstein',
    country: 'DE',
    district: 'Landkreis Traunstein',
    distance_km: 100,
    drive_minutes: 72,
    population: 20600,
    population_year: 2023,
    population_growth: '+5,4 % (2013–2023)',
    area_km2: 72.3,
    elevation_m: 591,
    founded: '1245 n. Chr.',
    description:
      'Traunstein ist Kreisstadt des gleichnamigen Landkreises im Chiemgau, bekannt als Geburtsort von Papst Benedikt XVI. und für das traditionelle Georgiritt.',
    history:
      'Traunstein wurde 1245 als Salzstadt gegründet. Papst Benedikt XVI. (Joseph Ratzinger) ist gebürtiger Bayer aus dieser Region – sein Vater war Gendarm in Traunstein. Der Georgiritt am Ostermontag ist einer der bekanntesten Pferdesegnungsritte Deutschlands.',
    sights: [
      'Stadtpfarrkirche St. Oswald',
      'Stadtturm und Altstadt',
      'Rathausplatz',
      'Chiemgauarena (Sport)',
      'Chiemsee (25 km)',
    ],
    known_for: 'Papst Benedikt XVI., Georgiritt, Chiemgau',
    ...calcPrice(100),
  },
  {
    slug: 'taxi-prien-am-chiemsee-flughafen-muenchen',
    name: 'Prien am Chiemsee',
    nameDE: 'Prien a. Chiemsee',
    country: 'DE',
    district: 'Landkreis Rosenheim',
    distance_km: 84,
    drive_minutes: 60,
    population: 10500,
    population_year: 2023,
    population_growth: '+5,9 % (2013–2023)',
    area_km2: 31.3,
    elevation_m: 533,
    description:
      'Prien am Chiemsee ist das Tor zum Chiemsee – dem „Bayerischen Meer". Von hier fahren Dampfboote zur Herreninsel mit Schloss Herrenchiemsee.',
    history:
      'Prien war seit dem Mittelalter ein wichtiger Marktort. Der Chiemsee und die Inseln wurden im 19. Jahrhundert durch König Ludwig II. bekannt, der auf der Herreninsel ein Spiegelsaal-Schloss nach dem Vorbild von Versailles errichtete. Heute ist Prien ein beliebter Ferienort und Ausflugsziel.',
    sights: [
      'Schloss Herrenchiemsee (König Ludwig II.)',
      'Dampfbootsfahrten auf dem Chiemsee',
      'Kloster Frauenchiemsee (Fraueninsel)',
      'Chiemseeufer Promenade Prien',
      'Kampenwand (Seilbahn, 1.669 m)',
    ],
    known_for: 'Chiemsee, Schloss Herrenchiemsee, König Ludwig II.',
    ...calcPrice(84),
  },
  {
    slug: 'taxi-landshut-flughafen-muenchen',
    name: 'Landshut',
    nameDE: 'Landshut',
    country: 'DE',
    district: 'kreisfreie Stadt',
    distance_km: 68,
    drive_minutes: 50,
    population: 75200,
    population_year: 2023,
    population_growth: '+7,1 % (2013–2023)',
    area_km2: 65.0,
    elevation_m: 393,
    founded: '1204 n. Chr.',
    description:
      'Landshut ist die Hauptstadt Niederbayerns, bekannt für die höchste Backsteinkirche der Welt (St. Martin), die Burg Trausnitz und die historische Landshuter Hochzeit.',
    history:
      'Landshut wurde 1204 von Herzog Ludwig I. gegründet und war im Mittelalter Residenzstadt der niederbayerischen Wittelsbacher. Die Landshuter Hochzeit von 1475 war das prächtigste Hochzeitsfest des Mittelalters und wird seit 1903 alle vier Jahre nachgestellt (nächstes Mal 2027). Die Altstadt mit der St.-Martins-Kirche (Turm: 130,6 m) ist ein bedeutendes Baudenkmal.',
    sights: [
      'St. Martin Kirche (höchster Backsteinturm der Welt)',
      'Burg Trausnitz',
      'Altstadt und Residenz Landshut',
      'Stadtresidenz (Italienischer Renaissancepalast)',
      'Isar-Ufer Promenade',
    ],
    known_for: 'Landshuter Hochzeit, St. Martin, Niederbayerische Hauptstadt',
    ...calcPrice(68),
  },
  {
    slug: 'taxi-straubing-flughafen-muenchen',
    name: 'Straubing',
    nameDE: 'Straubing',
    country: 'DE',
    district: 'kreisfreie Stadt',
    distance_km: 110,
    drive_minutes: 78,
    population: 48500,
    population_year: 2023,
    population_growth: '+4,3 % (2013–2023)',
    area_km2: 67.7,
    elevation_m: 323,
    founded: 'um 200 n. Chr.',
    description:
      'Straubing ist eine niederbayerische Stadt an der Donau, bekannt für das Gäubodenvolksfest (zweitgrößtes Volksfest Bayerns) und seinen Stadtturm.',
    history:
      'Straubing hat römische Wurzeln (Sorviodurum) und war im Mittelalter herzogliche Residenzstadt. Agnes Bernauer, eine Baderstochter, wurde 1435 im Auftrag des Herzogs in der Donau ertränkt – ihre Geschichte ist Teil der Stadtidentität. Das Gäubodenvolksfest zieht jährlich über eine Million Besucher an.',
    sights: [
      'Stadtturm Straubing',
      'Herzogliches Schloss',
      'Römermuseum (röm. Reiterpanzer)',
      'St.-Jakobs-Kirche',
      'Agnes-Bernauer-Gedenkstätte',
    ],
    known_for: 'Gäubodenvolksfest, Stadtturm, Donauufer',
    ...calcPrice(110),
  },
  {
    slug: 'taxi-passau-flughafen-muenchen',
    name: 'Passau',
    nameDE: 'Passau',
    country: 'DE',
    district: 'kreisfreie Stadt',
    distance_km: 185,
    drive_minutes: 120,
    population: 52200,
    population_year: 2023,
    population_growth: '+3,7 % (2013–2023)',
    area_km2: 70.1,
    elevation_m: 293,
    founded: 'um 100 n. Chr.',
    description:
      'Passau ist die „Dreiflüssestadt" – wo Donau, Inn und Ilz zusammenfließen – mit barocker Altstadt und dem Dom St. Stephan, Heimat der größten Dom-Orgel der Welt.',
    history:
      'Passau war als bischöfliche Residenzstadt und Handelsplatz jahrhundertelang eine der mächtigsten Städte Bayerns. Das Bistum Passau erstreckte sich einst bis nach Wien. Die barocke Altstadt auf der Halbinsel zwischen Donau und Inn gehört zu den schönsten Europas. Die historische Bedeutung spiegelt sich in zahlreichen Kirchen und Klöstern wider.',
    sights: [
      'Dom St. Stephan (größte Dom-Orgel der Welt)',
      'Veste Oberhaus (Stadtmuseum)',
      'Drei-Flüsse-Eck (Donau, Inn, Ilz)',
      'Altstadt mit Rathausplatz',
      'Glasmuseum Passau',
    ],
    known_for: 'Dreiflüssestadt, Dom-Orgel, Barockaltstadt',
    ...calcPrice(185),
  },
  {
    slug: 'taxi-regensburg-flughafen-muenchen',
    name: 'Regensburg',
    nameDE: 'Regensburg',
    country: 'DE',
    district: 'kreisfreie Stadt',
    distance_km: 123,
    drive_minutes: 85,
    population: 158000,
    population_year: 2023,
    population_growth: '+8,2 % (2013–2023)',
    area_km2: 80.7,
    elevation_m: 338,
    founded: '179 n. Chr.',
    description:
      'Regensburg ist die Hauptstadt der Oberpfalz mit UNESCO-Weltkulturerbe-Altstadt und einer der am besten erhaltenen mittelalterlichen Städte Europas.',
    history:
      'Das römische Castra Regina (179 n. Chr.) war Hauptsitz der Donaulegion. Im Mittelalter war Regensburg die größte Stadt nördlich der Alpen und Reichstagsstadt. Der Dom St. Peter, die Steinerne Brücke (1146) und das mittelalterliche Stadtbild machen Regensburg zu einem UNESCO-Weltkulturerbe. Heute ist BMW ein wichtiger Arbeitgeber.',
    sights: [
      'Steinerne Brücke (1146)',
      'Dom St. Peter (gotisch)',
      'Altstadt UNESCO-Weltkulturerbe',
      'Walhalla (15 km, Marmortempel)',
      'BMW Werk Regensburg',
    ],
    known_for: 'UNESCO-Altstadt, Steinerne Brücke, Mittelalterliches Erbe',
    ...calcPrice(123),
  },
  {
    slug: 'taxi-nuernberg-flughafen-muenchen',
    name: 'Nürnberg',
    nameDE: 'Nürnberg',
    country: 'DE',
    district: 'kreisfreie Stadt',
    distance_km: 168,
    drive_minutes: 110,
    population: 530000,
    population_year: 2023,
    population_growth: '+5,6 % (2013–2023)',
    area_km2: 186.4,
    elevation_m: 310,
    founded: 'um 1050 n. Chr.',
    description:
      'Nürnberg ist die zweitgrößte Stadt Bayerns, bekannt für die historische Altstadt, den weltberühmten Christkindlesmarkt und die Nürnberger Prozesse.',
    history:
      'Nürnberg war im Mittelalter als Freie Reichsstadt eine der bedeutendsten Städte des Heiligen Römischen Reiches. Albrecht Dürer, der bedeutendste deutsche Maler der Renaissance, wurde hier geboren. Im 20. Jahrhundert war Nürnberg Schauplatz der NS-Reichsparteitage und der Kriegsverbrecherprozesse. Die Altstadt wurde nach dem Krieg originalgetreu wiederaufgebaut.',
    sights: [
      'Nürnberger Burg',
      'Christkindlesmarkt (Advent)',
      'Germanisches Nationalmuseum',
      'Dokumentationszentrum Reichsparteitagsgelände',
      'Albrecht-Dürer-Haus',
    ],
    known_for: 'Christkindlesmarkt, Burg, Nürnberger Prozesse, Dürer',
    ...calcPrice(168),
  },
  {
    slug: 'taxi-kempten-flughafen-muenchen',
    name: 'Kempten (Allgäu)',
    nameDE: 'Kempten (Allgäu)',
    country: 'DE',
    district: 'kreisfreie Stadt',
    distance_km: 130,
    drive_minutes: 90,
    population: 69000,
    population_year: 2023,
    population_growth: '+6,3 % (2013–2023)',
    area_km2: 63.2,
    elevation_m: 674,
    founded: 'um 60 v. Chr.',
    description:
      'Kempten im Allgäu ist eine der ältesten Städte Deutschlands, bekannt als Wirtschaftszentrum des Allgäus und für seine römischen Ausgrabungsstätten.',
    history:
      'Kempten (Cambodunum) ist eine der ältesten Städte nördlich der Alpen. Als römische Provinzhauptstadt war sie bedeutender als Augsburg. Im Mittelalter wurde Kempten durch ein reiches Stift regiert. Die doppelte Stadtstruktur (Stiftsstadt und freie Reichsstadt) ist einzigartig in Deutschland.',
    sights: [
      'Archäologischer Park Cambodunum (Römer)',
      'Basilika St. Lorenz (Barockkirche)',
      'Residenz Kempten',
      'Allgäu-Museum',
      'Burghalde (Stadtpark)',
    ],
    known_for: 'Älteste Stadt Deutschlands, Römer-Park, Allgäu',
    ...calcPrice(130),
  },
  // ─── AUSTRIA ───────────────────────────────────────────────────────────────
  {
    slug: 'taxi-salzburg-flughafen-muenchen',
    name: 'Salzburg',
    nameDE: 'Salzburg',
    country: 'AT',
    district: 'Landeshauptstadt Salzburg',
    distance_km: 148,
    drive_minutes: 95,
    population: 156900,
    population_year: 2023,
    population_growth: '+7,2 % (2013–2023)',
    area_km2: 65.7,
    elevation_m: 424,
    founded: '696 n. Chr.',
    description:
      'Salzburg ist die Mozartstadt schlechthin – Geburtsort des Komponisten und UNESCO-Weltkulturerbe-Stadt an der Salzach mit barocker Altstadt und Festung Hohensalzburg.',
    history:
      'Salzburg war jahrhundertelang ein unabhängiges Fürsterzbistum, das durch den Salzhandel reich wurde. Wolfgang Amadeus Mozart wurde 1756 hier geboren. Die Festspiele (seit 1920) machen Salzburg zur internationalen Kulturmetropole. Die barocke Altstadt gehört seit 1997 zum UNESCO-Weltkulturerbe.',
    sights: [
      'Festung Hohensalzburg',
      'Mozarts Geburtshaus',
      'Dom zu Salzburg',
      'Mirabell-Gärten',
      'Salzburger Festspiele (Sommer)',
    ],
    known_for: 'Mozart, Festspiele, UNESCO-Altstadt, Salzach',
    ...calcPrice(148),
  },
  {
    slug: 'taxi-innsbruck-flughafen-muenchen',
    name: 'Innsbruck',
    nameDE: 'Innsbruck',
    country: 'AT',
    district: 'Landeshauptstadt Tirol',
    distance_km: 160,
    drive_minutes: 105,
    population: 136500,
    population_year: 2023,
    population_growth: '+6,8 % (2013–2023)',
    area_km2: 104.9,
    elevation_m: 574,
    founded: 'um 1180 n. Chr.',
    description:
      'Innsbruck ist die Hauptstadt Tirols, zweifacher Olympia-Austragungsort (1964, 1976) und liegt im Herz der Alpen am Zusammenfluss von Inn und Sill.',
    history:
      'Innsbruck war als habsburgische Residenzstadt eine der bedeutendsten Städte des Heiligen Römischen Reiches. Kaiser Maximilian I. (1459–1519) machte es zur kaiserlichen Residenz. Die Olympischen Winterspiele 1964 und 1976 sowie die Paralympischen Spiele prägten die moderne Stadtentwicklung. Die Goldene Dachl (1496) ist das bekannteste Wahrzeichen.',
    sights: [
      'Goldenes Dachl (15. Jh.)',
      'Hofburg Innsbruck',
      'Bergisel-Skischanze',
      'Nordkette Seilbahn (Stadtblick)',
      'Triumphpforte',
    ],
    known_for: 'Goldenes Dachl, Olympia, Tiroler Alpen, Habsburger',
    ...calcPrice(160),
  },
  {
    slug: 'taxi-kufstein-flughafen-muenchen',
    name: 'Kufstein',
    nameDE: 'Kufstein',
    country: 'AT',
    district: 'Bezirk Kufstein, Tirol',
    distance_km: 95,
    drive_minutes: 65,
    population: 20100,
    population_year: 2023,
    population_growth: '+5,3 % (2013–2023)',
    area_km2: 41.3,
    elevation_m: 499,
    founded: 'um 800 n. Chr.',
    description:
      'Kufstein ist eine Grenzstadt am Inn zwischen Bayern und Tirol, bekannt für die beeindruckende Festung Kufstein und als Tor zu den Tiroler Alpen.',
    history:
      'Kufstein war eine wichtige Grenzfeste und wechselte mehrmals zwischen Bayern und Österreich. Die Festung Kufstein (13. Jh.) ist eine der am besten erhaltenen Burganlagen der Alpen. Die Stadt war im 19. und 20. Jahrhundert bekannt für ihre Gitarrenmanufakturen (Stroh-Gitarre).',
    sights: [
      'Festung Kufstein',
      'Heldenorgel (größte Freiluftorgel der Welt)',
      'Inn-Ufer Promenade',
      'Kufsteinerland Bergbahnen',
      'Kaisergebirge (Kaiser-Klettersteig)',
    ],
    known_for: 'Festung, Heldenorgel, Inn-Grenzstadt, Tiroler Alpen',
    ...calcPrice(95),
  },
  {
    slug: 'taxi-woergl-flughafen-muenchen',
    name: 'Wörgl',
    nameDE: 'Wörgl',
    country: 'AT',
    district: 'Bezirk Kufstein, Tirol',
    distance_km: 100,
    drive_minutes: 68,
    population: 14400,
    population_year: 2023,
    population_growth: '+7,1 % (2013–2023)',
    area_km2: 20.9,
    elevation_m: 511,
    description:
      'Wörgl ist eine Tiroler Eisenbahnknotenstadt im Inntal, bekannt durch das „Wörgler Experiment" von 1932 – ein lokales Geldumlauf-Modell das weltweit Beachtung fand.',
    history:
      'Wörgl erlangte weltweite Bekanntheit durch das Freigeldexperiment (1932/33), mit dem Bürgermeister Michael Unterguggenberger die Arbeitslosigkeit in der Weltwirtschaftskrise bekämpfte. Als wichtiger Eisenbahnknotenpunkt verbindet Wörgl das Inntal mit dem Zillertal und dem Brixental.',
    sights: [
      'Gedächtnismuseum Freigeld-Experiment',
      'Stadtpfarrkirche Wörgl',
      'Inn-Auen (Naherholung)',
      'Brixental (Kitzbühel Alpen, 15 km)',
      'Zahmer Kaiser (Wandergebiet)',
    ],
    known_for: 'Wörgler Experiment, Inntal-Knoten, Tiroler Unterland',
    ...calcPrice(100),
  },
  {
    slug: 'taxi-kitzbuehl-flughafen-muenchen',
    name: 'Kitzbühel',
    nameDE: 'Kitzbühel',
    country: 'AT',
    district: 'Bezirk Kitzbühel, Tirol',
    distance_km: 118,
    drive_minutes: 80,
    population: 8600,
    population_year: 2023,
    population_growth: '+3,9 % (2013–2023)',
    area_km2: 75.2,
    elevation_m: 762,
    founded: 'um 1270 n. Chr.',
    description:
      'Kitzbühel ist eines der exklusivsten Wintersport- und Luxusresorts der Alpen, weltbekannt durch die Hahnenkamm-Rennen und als Sommerfrischeort.',
    history:
      'Kitzbühel wurde im Mittelalter durch Silber- und Kupferbergbau reich. Im 19. Jahrhundert entdeckten reiche Münchner und Wiener den Ort als Sommerfrische. Heute ist Kitzbühel Inbegriff von Luxus-Alpentourismus. Die Hahnenkamm-Rennen (jährlich im Januar) sind die anspruchsvollste Abfahrt im Weltcup-Zirkus.',
    sights: [
      'Hahnenkamm Seilbahn',
      'Streif (Hahnenkamm-Abfahrt)',
      'Altstadt Kitzbühel (mittelalterlich)',
      'Kitzbüheler Horn',
      'Hintersteiner See',
    ],
    known_for: 'Hahnenkamm-Rennen, Luxus-Skiresort, Tiroler Alpen',
    ...calcPrice(118),
  },
  {
    slug: 'taxi-bregenz-flughafen-muenchen',
    name: 'Bregenz',
    nameDE: 'Bregenz',
    country: 'AT',
    district: 'Landeshauptstadt Vorarlberg',
    distance_km: 200,
    drive_minutes: 130,
    population: 30600,
    population_year: 2023,
    population_growth: '+5,8 % (2013–2023)',
    area_km2: 35.7,
    elevation_m: 398,
    founded: 'um 15 v. Chr.',
    description:
      'Bregenz ist die Hauptstadt Vorarlbergs am Bodensee, weltbekannt für die Bregenzer Festspiele mit der spektakulären Seebühne – die größte Freilichtbühne der Welt.',
    history:
      'Brigantium war ein wichtiger römischer Militärstützpunkt am Bodensee. Im Mittelalter war Bregenz Hauptort der Grafschaft Bregenz. Die Bregenzer Festspiele (seit 1946) haben die Stadt zu einem internationalen Kulturzentrum gemacht. Das Vorarlberg Museum zeigt 30.000 Jahre Landesgeschichte.',
    sights: [
      'Seebühne der Bregenzer Festspiele',
      'Pfänder (Seilbahn, 1.064 m)',
      'Vorarlberg Museum',
      'Altstadt Oberstadt',
      'Bodensee-Uferpromenade',
    ],
    known_for: 'Bregenzer Festspiele, Bodensee, Seebühne',
    ...calcPrice(200),
  },
  {
    slug: 'taxi-rosenheim-austria-flughafen-muenchen',
    name: 'Kufstein Umgebung / St. Johann',
    nameDE: 'St. Johann in Tirol',
    country: 'AT',
    district: 'Bezirk Kitzbühel, Tirol',
    distance_km: 105,
    drive_minutes: 72,
    population: 8900,
    population_year: 2023,
    population_growth: '+4,7 % (2013–2023)',
    area_km2: 62.4,
    elevation_m: 659,
    description:
      'St. Johann in Tirol ist ein beliebter Tiroler Ferienort im Kitzbüheler Alpengebiet, Ausgangspunkt für Sommer- und Winterurlauber.',
    history:
      'St. Johann in Tirol erhielt im 14. Jahrhundert Marktrecht und war ein wichtiger Umschlagsplatz im Transithandel durch das Inntal. Das Wahrzeichen ist die Pfarrkirche Mariä Himmelfahrt (Barock, 1728). Der Ort entwickelte sich im 20. Jahrhundert zum Tourismuszentrum.',
    sights: [
      'Pfarrkirche Mariä Himmelfahrt',
      'Kitzbüheler Alpen Wanderwege',
      'Skigebiet St. Johann',
      'Pillersee (Naherholung)',
      'Wilder Kaiser (Bergmassiv)',
    ],
    known_for: 'Kitzbüheler Alpen, Sommer- und Wintertourismus, Inntal',
    ...calcPrice(105),
  },
  {
    slug: 'taxi-zell-am-see-flughafen-muenchen',
    name: 'Zell am See',
    nameDE: 'Zell am See',
    country: 'AT',
    district: 'Bezirk Zell am See, Salzburg',
    distance_km: 195,
    drive_minutes: 125,
    population: 10300,
    population_year: 2023,
    population_growth: '+6,2 % (2013–2023)',
    area_km2: 74.0,
    elevation_m: 757,
    description:
      'Zell am See ist ein Tiroler Tourismuszentrum am gleichnamigen See im Pinzgau, ganzjährig beliebtes Ski- und Wandergebiet mit Gletscher Kitzsteinhorn.',
    history:
      'Zell am See entwickelte sich im 19. Jahrhundert vom Fischerort zum Tourismusdestination, nachdem die Tauernbahn (1909) die Erschließung ermöglichte. Das Kitzsteinhorn mit seinem Gletscher (3.203 m) macht Zell am See zum ganzjährigen Skigebiet. Europas größtes Sommerskigebiet liegt auf dem Gletscher.',
    sights: [
      'Kitzsteinhorn Gletscher (Sommerskifahren)',
      'Zeller See (Strandbad)',
      'Schmittenhöhe (Seilbahn)',
      'Altstadt Zell am See',
      'Kaprun Wasserkraftwerk (Tour)',
    ],
    known_for: 'Kitzsteinhorn, Gletscherskifahren, Zeller See',
    ...calcPrice(195),
  },
  // ─── SWITZERLAND ───────────────────────────────────────────────────────────
  {
    slug: 'taxi-zuerich-flughafen-muenchen',
    name: 'Zürich',
    nameDE: 'Zürich',
    country: 'CH',
    district: 'Kanton Zürich',
    distance_km: 310,
    drive_minutes: 190,
    population: 441300,
    population_year: 2023,
    population_growth: '+8,4 % (2013–2023)',
    area_km2: 88.1,
    elevation_m: 408,
    founded: 'um 15 v. Chr.',
    description:
      'Zürich ist die größte Stadt der Schweiz und das Finanz- und Wirtschaftszentrum des Landes, gelegen am Zürichsee mit direktem Blick auf die Alpen.',
    history:
      'Turicum war ein römischer Zollposten. Im Mittelalter wurde Zürich zur bedeutenden Handelsstadt. Die Reformation unter Huldrych Zwingli (1519) begann in Zürich. Heute ist Zürich eines der wichtigsten globalen Finanzzentren und regelmäßig unter den lebenswertesten Städten der Welt.',
    sights: [
      'Altstadt (Niederdorf)',
      'Kunsthaus Zürich',
      'Grossmünster und Fraumünster',
      'Uetliberg (Aussichtsberg)',
      'Zürichsee Schifffahrten',
    ],
    known_for: 'Finanzplatz, Altstadt, Zürichsee, Grossmünster',
    ...calcPrice(310),
  },
  {
    slug: 'taxi-bern-flughafen-muenchen',
    name: 'Bern',
    nameDE: 'Bern',
    country: 'CH',
    district: 'Kanton Bern',
    distance_km: 420,
    drive_minutes: 255,
    population: 137000,
    population_year: 2023,
    population_growth: '+5,2 % (2013–2023)',
    area_km2: 51.6,
    elevation_m: 542,
    founded: '1191 n. Chr.',
    description:
      'Bern ist die Bundesstadt der Schweiz mit einer der besterhaltenen mittelalterlichen Innenstädte Europas, die zum UNESCO-Weltkulturerbe gehört.',
    history:
      'Bern wurde 1191 von Herzog Berthold V. von Zähringen gegründet. Seit 1848 ist es Sitz der Bundesbehörden der Schweiz. Albert Einstein lebte und arbeitete hier (Haus am Kramgasse), als er 1905 die Relativitätstheorie entwickelte. Die Altstadt mit ihren 6 km langen Lauben ist einzigartig in Europa.',
    sights: [
      'Altstadt UNESCO-Weltkulturerbe',
      'Zytglogge (Zeitglockenturm)',
      'Berner Münster',
      'Bärenpark (Wappentier)',
      'Zentrum Paul Klee',
    ],
    known_for: 'Bundesstadt, Altstadt, Einstein, Zytglogge',
    ...calcPrice(420),
  },
  {
    slug: 'taxi-basel-flughafen-muenchen',
    name: 'Basel',
    nameDE: 'Basel',
    country: 'CH',
    district: 'Kanton Basel-Stadt',
    distance_km: 360,
    drive_minutes: 220,
    population: 178000,
    population_year: 2023,
    population_growth: '+5,9 % (2013–2023)',
    area_km2: 23.9,
    elevation_m: 260,
    founded: 'um 44 v. Chr.',
    description:
      'Basel ist die Kulturhauptstadt der Schweiz, bekannt als Gastgeberstadt der Art Basel (weltgrößte Kunstmesse) und für die Pharmaindustrie (Novartis, Roche).',
    history:
      'Basel war als Bischofssitz und Handelsplatz am Rhein seit dem Mittelalter bedeutend. Die Universität Basel (1460) ist die älteste der Schweiz. Erasmus von Rotterdam lehrte hier. Heute ist Basel mit dem Dreiländereck (D/F/CH) ein europäisches Zentrum und Heimat der weltweit bedeutendsten Kunstmesse Art Basel.',
    sights: [
      'Basler Münster',
      'Kunstmuseum Basel (größte Kunstsammlung der Schweiz)',
      'Art Basel (Kunst-Messe, Juni)',
      'Fondation Beyeler',
      'Mittlere Rheinbrücke und Rheinufer',
    ],
    known_for: 'Art Basel, Kunst, Pharmastandort, Dreiländereck',
    ...calcPrice(360),
  },
  {
    slug: 'taxi-st-gallen-flughafen-muenchen',
    name: 'St. Gallen',
    nameDE: 'St. Gallen',
    country: 'CH',
    district: 'Kanton St. Gallen',
    distance_km: 250,
    drive_minutes: 160,
    population: 80000,
    population_year: 2023,
    population_growth: '+7,1 % (2013–2023)',
    area_km2: 39.3,
    elevation_m: 669,
    founded: '612 n. Chr.',
    description:
      'St. Gallen ist das wirtschaftliche Zentrum der Ostschweiz, bekannt für das UNESCO-Weltkulturerbe Stiftsbibliothek und das traditionsreiche Stickerei-Gewerbe.',
    history:
      'Das Kloster St. Gallen (612 gegründet) war im Mittelalter eines der wichtigsten Kulturzentren Europas. Die Stiftsbibliothek beherbergt über 170.000 Bücher, darunter unschätzbare mittelalterliche Handschriften. Im 19. Jahrhundert war St. Gallen weltweit führend in der Spitzen- und Stickerei-Produktion.',
    sights: [
      'Stiftsbibliothek St. Gallen (UNESCO)',
      'Kathedrale St. Gallen',
      'Textilmuseum',
      'Stadtpark',
      'Bodensee (20 km)',
    ],
    known_for: 'Stiftsbibliothek, Stickerei, UNESCO-Kulturerbe',
    ...calcPrice(250),
  },
  {
    slug: 'taxi-konstanz-flughafen-muenchen',
    name: 'Konstanz',
    nameDE: 'Konstanz',
    country: 'DE',
    district: 'Landkreis Konstanz, Baden-Württemberg',
    distance_km: 168,
    drive_minutes: 115,
    population: 84300,
    population_year: 2023,
    population_growth: '+6,3 % (2013–2023)',
    area_km2: 57.7,
    elevation_m: 407,
    founded: '300 n. Chr.',
    description:
      'Konstanz liegt am Bodensee (Grenze CH/DE) und ist die größte Stadt am See, bekannt für das Konzil von Konstanz (1414–1418) und die Universität.',
    history:
      'Das Konzil von Konstanz (1414–1418) war das bedeutendste Kirchentreffen des Mittelalters – hier wurde Jan Hus verbrannt und der Kirchenschisma beendet. Im Zweiten Weltkrieg blieb Konstanz unzerstört, weil es seine Lichter nicht verdunkelte und alliierte Bomber es für eine Schweizer Stadt hielten.',
    sights: [
      'Konzilgebäude',
      'Konstanzer Münster',
      'Bodensee-Uferpromenade',
      'Imperia-Skulptur im Hafen',
      'Insel Mainau (Blumeninsel, 8 km)',
    ],
    known_for: 'Konzil von Konstanz, Bodensee, Grenzstadt',
    ...calcPrice(168),
  },
  {
    slug: 'taxi-lindau-flughafen-muenchen',
    name: 'Lindau im Bodensee',
    nameDE: 'Lindau (Bodensee)',
    country: 'DE',
    district: 'Landkreis Lindau, Bayern',
    distance_km: 190,
    drive_minutes: 125,
    population: 25200,
    population_year: 2023,
    population_growth: '+4,8 % (2013–2023)',
    area_km2: 33.0,
    elevation_m: 398,
    founded: 'um 1000 n. Chr.',
    description:
      'Lindau liegt auf einer Insel im Bodensee und ist ein malerisches Städtchen mit mittelalterlicher Altstadt, bekannt für das Nobelpreisträger-Treffen.',
    history:
      'Lindau war als freie Reichsstadt am Bodensee ein bedeutender Handelsplatz. Die Altstadtinsel ist mit einer Brücke und einer Eisenbahn mit dem Festland verbunden. Seit 1951 treffen sich jährlich Nobelpreisträger in Lindau – ein einzigartiges wissenschaftliches Forum.',
    sights: [
      'Altstadtinsel mit mittelalterlichem Stadtbild',
      'Mangturm und Bayerischer Löwe (Hafeneinfahrt)',
      'Peterskirche mit Wandgemälden von Hans Holbein',
      'Bodensee-Seepromenade',
      'Nobelpreisträger-Tagungen (Juni/Juli)',
    ],
    known_for: 'Bodensee-Insel, Nobelpreisträger-Treffen, Altstadt',
    ...calcPrice(190),
  },
  {
    slug: 'taxi-friedrichshafen-flughafen-muenchen',
    name: 'Friedrichshafen',
    nameDE: 'Friedrichshafen',
    country: 'DE',
    district: 'Bodenseekreis, Baden-Württemberg',
    distance_km: 175,
    drive_minutes: 118,
    population: 61100,
    population_year: 2023,
    population_growth: '+5,1 % (2013–2023)',
    area_km2: 60.0,
    elevation_m: 399,
    founded: '1811 n. Chr.',
    description:
      'Friedrichshafen am Bodensee ist Heimat von Zeppelin, Airbus (DASA), Dornier und der Messe Friedrichshafen – ein bedeutender Industrie- und Technologiestandort.',
    history:
      'Graf Ferdinand von Zeppelin baute hier 1900 das erste starre Luftschiff (LZ 1). Die Zeppelinhallen am Bodensee wurden zu einem Wahrzeichen des Ortes. Im Zweiten Weltkrieg stark zerstört, wurde Friedrichshafen zum modernen Industriestandort mit Firmen wie ZF, Airbus und MTU.',
    sights: [
      'Zeppelin Museum Friedrichshafen',
      'Zeppelin-Werft (Nachfolgebetrieb)',
      'Bodensee-Uferpromenade',
      'Messe Friedrichshafen',
      'Schloss Friedrichshafen',
    ],
    known_for: 'Zeppelin, Luftschiffbau, ZF Friedrichshafen, Bodensee',
    ...calcPrice(175),
  },
  {
    slug: 'taxi-ulm-flughafen-muenchen',
    name: 'Ulm',
    nameDE: 'Ulm',
    country: 'DE',
    district: 'kreisfreie Stadt, Baden-Württemberg',
    distance_km: 145,
    drive_minutes: 98,
    population: 126800,
    population_year: 2023,
    population_growth: '+5,7 % (2013–2023)',
    area_km2: 118.7,
    elevation_m: 479,
    founded: 'um 850 n. Chr.',
    description:
      'Ulm ist die Geburtsstadt von Albert Einstein und beherbergt das Ulmer Münster mit dem höchsten Kirchturm der Welt (161,53 m).',
    history:
      'Ulm war als freie Reichsstadt und Handelsmetropole im Mittelalter bedeutend. Die Wollweberei machte die Stadt reich. Der Tailor of Ulm versuchte 1811 den ersten Flugversuch. Albert Einstein wurde 1879 in Ulm geboren. Das Ulmer Münster (Grundsteinlegung 1377) wurde erst 1890 vollendet.',
    sights: [
      'Ulmer Münster (höchster Kirchturm der Welt, 161 m)',
      'Fischerviertel (Altstadt)',
      'Albert-Einstein-Geburtshaus (Gedenktafel)',
      'Stadtmauer und Metzgerturm',
      'Museum Ulm',
    ],
    known_for: 'Ulmer Münster, Einstein, Donauufer',
    ...calcPrice(145),
  },
  {
    slug: 'taxi-chur-flughafen-muenchen',
    name: 'Chur',
    nameDE: 'Chur',
    country: 'CH',
    district: 'Kanton Graubünden',
    distance_km: 280,
    drive_minutes: 175,
    population: 38000,
    population_year: 2023,
    population_growth: '+6,5 % (2013–2023)',
    area_km2: 28.0,
    elevation_m: 596,
    founded: 'vor 5000 Jahren',
    description:
      'Chur ist die älteste Stadt der Schweiz (ca. 3000 v. Chr. besiedelt) und die Hauptstadt Graubündens, ein wichtiger Knotenpunkt für Rhätische Bahn und Glacier Express.',
    history:
      'Chur ist eine der ältesten kontinuierlich besiedelten Städte Europas. Die Römer nannten es Curia Raetorum. Das Bischofsstift (5. Jh.) prägte die mittelalterliche Geschichte. Heute ist Chur als Startpunkt des Glacier Express ein bedeutender Tourismusknoten für Graubünden.',
    sights: [
      'Churer Dom (romanisch-gotisch)',
      'Bischöflicher Hof',
      'Rätisches Museum',
      'Altstadt mit engen Gassen',
      'Glacier Express Startbahnhof',
    ],
    known_for: 'Älteste Schweizer Stadt, Glacier Express, Graubünden',
    ...calcPrice(280),
  },
  {
    slug: 'taxi-davos-flughafen-muenchen',
    name: 'Davos',
    nameDE: 'Davos',
    country: 'CH',
    district: 'Kanton Graubünden',
    distance_km: 305,
    drive_minutes: 195,
    population: 11400,
    population_year: 2023,
    population_growth: '+2,8 % (2013–2023)',
    area_km2: 254.2,
    elevation_m: 1560,
    description:
      'Davos ist das weltweit bekannteste Bergdorf – Austragungsort des Weltwirtschaftsforums (WEF) und Wintersportort auf dem höchsten europäischen Plateau.',
    history:
      'Davos entwickelte sich im 19. Jahrhundert zum Sanatoriums-Ort für Tuberkulose-Patienten (hohe Höhe, klare Luft). Der Schriftsteller Thomas Mann beschrieb Davos in seinem Roman „Der Zauberberg" (1924). Seit 1971 ist das World Economic Forum (WEF) ein prägender Jahreshöhepunkt.',
    sights: [
      'Jakobshorn Skigebiet',
      'Parsenn (weltgrößtes Skigebiet)',
      'Kirchner Museum Davos',
      'Davoser See',
      'WEF-Kongresszentrum',
    ],
    known_for: 'Weltwirtschaftsforum, Skigebiet Parsenn, Der Zauberberg',
    ...calcPrice(305),
  },
  {
    slug: 'taxi-luzern-flughafen-muenchen',
    name: 'Luzern',
    nameDE: 'Luzern',
    country: 'CH',
    district: 'Kanton Luzern',
    distance_km: 340,
    drive_minutes: 210,
    population: 83000,
    population_year: 2023,
    population_growth: '+6,9 % (2013–2023)',
    area_km2: 29.1,
    elevation_m: 435,
    founded: 'um 840 n. Chr.',
    description:
      'Luzern ist eine der meistbesuchten Städte der Schweiz, bekannt für die Kapellbrücke (älteste gedeckte Holzbrücke Europas), den Vierwaldstättersee und die Alpenkulisse.',
    history:
      'Luzern war im Mittelalter als Marktstadt und Übergangsort auf dem Weg nach Italien bedeutend. Die Kapellbrücke (1333) ist das Wahrzeichen der Stadt. Das Löwendenkmal (1821), ein in Fels gemeißelter Löwe, erinnert an die in Paris gefallenen Schweizer Garde-Soldaten.',
    sights: [
      'Kapellbrücke und Wasserturm',
      'Löwendenkmal',
      'Rigi (Königin der Berge, Zahnradbahn)',
      'Verkehrshaus der Schweiz',
      'Vierwaldstättersee Schifffahrt',
    ],
    known_for: 'Kapellbrücke, Vierwaldstättersee, Rigi, Schweizer Herz',
    ...calcPrice(340),
  },
  {
    slug: 'taxi-winterthur-flughafen-muenchen',
    name: 'Winterthur',
    nameDE: 'Winterthur',
    country: 'CH',
    district: 'Kanton Zürich',
    distance_km: 300,
    drive_minutes: 185,
    population: 116000,
    population_year: 2023,
    population_growth: '+7,8 % (2013–2023)',
    area_km2: 68.1,
    elevation_m: 439,
    founded: 'um 294 n. Chr.',
    description:
      'Winterthur ist die sechstgrößte Stadt der Schweiz, bekannt für ihre bedeutenden Museen (Kunstmuseum, Fotomuseum) und als ehemalige Industriestadt (Sulzer, Rieter).',
    history:
      'Winterthur war im 19. Jahrhundert eines der bedeutendsten Industriezentren Europas mit Maschinenbau-Unternehmen wie Sulzer und Rieter. Die wohlhabenden Industriellen förderten Kunst und Kultur – so entstand eine der bedeutendsten Kunstsammlungen der Schweiz.',
    sights: [
      'Kunstmuseum Winterthur',
      'Fotomuseum Winterthur',
      'Technorama (Science Center)',
      'Altstadt Winterthur',
      'Schloss Kyburg (15 km)',
    ],
    known_for: 'Museumsstadt, Industriegeschichte, Sulzer',
    ...calcPrice(300),
  },
];

export const citiesBySlug: Record<string, CityData> = Object.fromEntries(
  cities.map((c) => [c.slug, c])
);

export const allCitySlugs = cities.map((c) => c.slug);

export default cities;
