export interface CityTranslationEn {
  description: string;
  history: string;
  known_for: string;
  sights: string[];
  // page UI
  intro: string; // opening paragraph in transfer section
}

const en: Record<string, CityTranslationEn> = {
  'taxi-dachau-flughafen-muenchen': {
    description: 'Dachau is a major district town in the Dachau district, located northwest of Munich and part of the greater Munich metropolitan area.',
    history: 'Dachau was founded as a market settlement in the Middle Ages and was known until the 19th century for its paper mills and later for the Dachau Artists\' Colony, which attracted many Impressionist painters. In the 20th century the name became known worldwide due to the first Nazi concentration camp, established in 1933 on a former munitions factory site. Today Dachau is a modern residential town with a vibrant art scene.',
    known_for: 'Artists\' Colony, KZ Memorial Site, Munich suburbs',
    sights: ['KZ-Gedenkstätte Dachau (Memorial)', 'Schloss Dachau & Hofgarten', 'Alte Münchner Straße (Artists\' Quarter)', 'Old Town Dachau', 'Town Hall and St. Jakob Church'],
    intro: 'From Dachau to Munich Airport (MUC) the distance is approx. {km} km. With our fixed-price taxi service you will reach Terminal 1 or Terminal 2 in about {min} minutes – stress-free and punctual.',
  },
  'taxi-augsburg-flughafen-muenchen': {
    description: 'Augsburg is the third-largest city in Bavaria and one of the oldest cities in Germany, founded by the Romans as Augusta Vindelicum around 15 BC.',
    history: 'As a Roman provincial capital and major trading metropolis in the Middle Ages, Augsburg was home to the banking families Fugger and Welser, who shaped world trade. The Peace of Augsburg in 1555 ended the first religious war in Europe. Today Augsburg hosts major industrial companies such as MAN, KUKA and Premium Aerotec.',
    known_for: 'Fugger dynasty, Roman history, UNESCO Water Management System',
    sights: ['Augsburg Cathedral', 'Fuggerei – oldest social housing estate in the world', 'Golden Hall in the Town Hall', 'Schaezlerpalais & State Gallery', 'Red Gate and historic city walls'],
    intro: 'From Augsburg to Munich Airport the distance is approx. {km} km via the A8 motorway. Our fixed-price taxi gets you to MUC in about {min} minutes.',
  },
  'taxi-ingolstadt-flughafen-muenchen': {
    description: 'Ingolstadt is the fourth-largest city in Bavaria, known as the headquarters of Audi and as a historic fortress city on the Danube.',
    history: 'Ingolstadt was the residence of the Wittelsbach dukes and hosted Bavaria\'s first university from 1472. The massive 19th-century fortifications (Festung Ingolstadt) are still partly preserved. In the city walls the novel "Frankenstein" was inspired by Mary Shelley in 1800. Today Audi dominates the city as its largest employer.',
    known_for: 'Audi headquarters, university city, Danube fortress',
    sights: ['Audi Museum Mobile', 'Bavarian Army Museum in Neues Schloss', 'Liebfrauenmünster Cathedral', 'Fortress with Reduit Tilly', 'Klenzepark on the Danube'],
    intro: 'From Ingolstadt to Munich Airport it\'s approx. {km} km along the A9. Our taxi service covers the journey in around {min} minutes at a guaranteed fixed price.',
  },
  'taxi-rosenheim-flughafen-muenchen': {
    description: 'Rosenheim is an independent city in Upper Bavaria, located on the Inn River between Munich and the Alps, and serves as an important shopping and industrial centre for the region.',
    history: 'Rosenheim emerged as a salt transshipment point on the Inn in the Middle Ages and received its town charter in 1328. Salt and timber trade made the town prosperous. In the 19th century the railway connected Rosenheim to Munich and the Brenner Pass, driving industrial development.',
    known_for: 'Inn Valley, gateway to the Alps, glass industry',
    sights: ['Rosenheim City Museum', 'Mangfall Park and Inn embankment', 'Max-Josefs-Platz with historic arcades', 'Rosenheim Art Museum', 'Wendelstein mountain (47 km)'],
    intro: 'The journey from Rosenheim to Munich Airport covers approx. {km} km. Our taxi picks you up door-to-door and delivers you to MUC Terminal 1 or 2 in around {min} minutes.',
  },
  'taxi-freising-flughafen-muenchen': {
    description: 'Freising is located right next to Munich Airport and is one of the oldest episcopal cities in Bavaria with over 1,300 years of history.',
    history: 'Freising was for centuries the ecclesiastical and cultural centre of Bavaria, even before Munich. The Cathedral Hill with the Dom and Diocesan Museum is one of the most important medieval ensembles in southern Germany. The Weihenstephan Brewery (founded 1040) is considered the world\'s oldest brewery. Pope Benedict XVI was ordained a priest in Freising.',
    known_for: 'Cathedral Hill, world\'s oldest brewery, adjacent to Munich Airport',
    sights: ['Freising Cathedral (Dom St. Maria und St. Korbinian)', 'Diocesan Museum Freising', 'Weihenstephan – world\'s oldest brewery', 'Old Town with Marienplatz', 'Cathedral Hill viewing terrace'],
    intro: 'Freising is the closest major town to Munich Airport – only {km} km away. Our taxi transfer takes just {min} minutes.',
  },
  'taxi-landsberg-am-lech-flughafen-muenchen': {
    description: 'Landsberg am Lech is a picturesque small town on the Romantic Road, known for its Baroque old town and impressive town walls.',
    history: 'Duke Henry the Lion founded Landsberg in the 12th century as a toll station on the Lech. The town flourished in the Middle Ages thanks to the salt trade. In the 15th century the still-preserved town walls were built. Adolf Hitler wrote "Mein Kampf" here during his imprisonment in 1923/24.',
    known_for: 'Romantic Road, Bayertor gate, Lech riverside',
    sights: ['Town walls and Bayertor gate', 'Main square with historic townhouses', 'Johanniskirche', 'Lechwehr and riverside promenade', 'Landsberg City Museum'],
    intro: 'From Landsberg am Lech to Munich Airport is approx. {km} km. Our fixed-price taxi brings you to MUC in around {min} minutes, door to door.',
  },
  'taxi-erding-flughafen-muenchen': {
    description: 'Erding lies east of Munich Airport and is famous for its thermal spa, its Weissbier, and as one of the fastest-growing district towns in the Munich commuter belt.',
    history: 'Erding received its town charter in the 14th century and was an important stop on the salt road from Salzburg to Augsburg. In the 20th century the town was strongly shaped by the nearby Munich Airport, which has been operating since 1992.',
    known_for: 'Therme Erding (Germany\'s largest spa), Erdinger Weissbier, proximity to Munich Airport',
    sights: ['Therme Erding – Germany\'s largest thermal spa', 'Old Town with Schöner Turm', 'Frauenkirche Erding', 'Erdinger Weissbräu (brewery)', 'Lengdorfer Weiher (lake)'],
    intro: 'Erding is just {km} km from Munich Airport. Our taxi gets you there in only {min} minutes – ideal for early morning flights.',
  },
  'taxi-ebersberg-flughafen-muenchen': {
    description: 'Ebersberg is a district town east of Munich and the gateway to the Ebersberg Forest – Bavaria\'s largest contiguous woodland.',
    history: 'A Benedictine monastery founded in 924 was the origin of the settlement. In the 19th century Ebersberg received its town charter and a railway connection. The monastery was secularised, but the Romanesque monastery church survives. The surrounding Ebersberg Forest covers 10,000 hectares.',
    known_for: 'Ebersberg Forest, monastery church, Munich\'s eastern outskirts',
    sights: ['Klosterkirche St. Sebastian', 'Ebersberg Forest – Bavaria\'s largest woodland', 'Old Town Hall', 'Ebersberg City Museum', 'Grafing Lake (recreation)'],
    intro: 'From Ebersberg to Munich Airport the distance is approx. {km} km. Our taxi service takes around {min} minutes.',
  },
  'taxi-starnberg-flughafen-muenchen': {
    description: 'Starnberg is located on the northern shore of Lake Starnberg, one of Bavaria\'s most famous lakes, and is regarded as an exclusive residential location in the Munich commuter belt.',
    history: 'Starnberg developed in the 19th century into a popular summer retreat for Munich residents and the Bavarian aristocracy. King Ludwig II drowned in Lake Starnberg in 1886 under unexplained circumstances. The Starnberg district is one of the wealthiest in Germany.',
    known_for: 'Lake Starnberg, King Ludwig II, Alpine panorama',
    sights: ['Lake Starnberg – boat trips & promenades', 'Votive Chapel in memory of King Ludwig II', 'Schloss Berg (private, exterior view)', 'Museum Starnberger See', 'Sailing regattas in summer'],
    intro: 'From Starnberg to Munich Airport is approx. {km} km. Our taxi brings you to MUC in around {min} minutes – comfortable and on time.',
  },
  'taxi-wolfratshausen-flughafen-muenchen': {
    description: 'Wolfratshausen lies on the Loisach south of Munich and is the starting point for traditional raft trips on the Isar River.',
    history: 'The town at the confluence of the Loisach and Isar was an important trading place in the Middle Ages. Raftsmen transported timber and salt from the Alps to Munich for centuries. This tradition of raft trips lives on today as a popular tourist attraction.',
    known_for: 'Isar raft trips, Loisach, Alpine foothills',
    sights: ['Floßlände – departure point for legendary Isar raft trips', 'Old Town with Marienplatz', 'Loisach riverside promenade', 'Waldmuseum Wolfratshausen', 'Kloster Beuerberg (12 km)'],
    intro: 'From Wolfratshausen to Munich Airport the journey covers approx. {km} km. Our fixed-price taxi delivers you to MUC in about {min} minutes.',
  },
  'taxi-bad-toelz-flughafen-muenchen': {
    description: 'Bad Tölz is a well-known spa town on the Isar with one of Bavaria\'s most beautiful old towns and a strong tradition of folk costumes and marksmen\'s associations.',
    history: 'Bad Tölz was an important trading town on the salt road in the Middle Ages. From the 19th century it developed into a spa resort thanks to its iodine springs. The picturesque old town with its colourfully painted townhouses along Marktstraße remains a landmark. The Leonhardifahrt procession in November is one of Bavaria\'s most famous.',
    known_for: 'Spa resort, iodine springs, Leonhardifahrt procession',
    sights: ['Marktstrasse with historic Lüftlmalerei paintings', 'Kalvarienberg with Heilig-Kreuz-Kirche', 'Alpamare thermal & leisure pool', 'Bad Tölz City Museum', 'Blomberg (summer toboggan & hiking)'],
    intro: 'From Bad Tölz to Munich Airport is approx. {km} km. Our taxi covers this route in about {min} minutes at a fixed price.',
  },
  'taxi-miesbach-flughafen-muenchen': {
    description: 'Miesbach is the district town of the Miesbach district in Upper Bavarian Alpine foothills and a gateway for trips into the Bavarian Alps.',
    history: 'Miesbach received its market charter in the 13th century and was an important trading point on the road to Salzburg. The brewing tradition is deeply rooted – Miesbacher beer was widely traded until the 19th century. The Miesbach district is one of the most scenic and economically strongest regions in Bavaria.',
    known_for: 'Alpine foothills, Tegernsee-Schliersee region, mountain panorama',
    sights: ['Stadtpfarrkirche Mariä Himmelfahrt', 'Schlossanger Alp (hiking & skiing)', 'Wendelstein (1,838 m, cable car)', 'Schliersee (12 km)', 'Tegernsee (18 km)'],
    intro: 'From Miesbach to Munich Airport it\'s approx. {km} km. Our taxi gets you there in around {min} minutes.',
  },
  'taxi-weilheim-flughafen-muenchen': {
    description: 'Weilheim in Oberbayern is a small town south of Munich in the Alpine foothills and the main shopping centre for the region between Lake Ammer and the Alps.',
    history: 'Weilheim received its town charter in 1330 and was a significant market town. Located near several lakes (Ammersee, Starnberger See, Staffelsee), it is a popular base for water sports and nature activities.',
    known_for: 'Alpine foothills, lake landscape, historic old town',
    sights: ['Stadtpfarrkirche Mariä Himmelfahrt', 'Town tower and historic market square', 'Ammersee (15 km)', 'Staffelsee (20 km)', 'Wessobrunn Monastery (12 km)'],
    intro: 'From Weilheim to Munich Airport the distance is approx. {km} km. Our fixed-price taxi covers the route in about {min} minutes.',
  },
  'taxi-schongau-flughafen-muenchen': {
    description: 'Schongau is a historic Lech town on a high plateau, part of the Romantic Road with a nearly completely preserved medieval town wall.',
    history: 'Schongau was an important trading and transshipment point on the Lech in the Middle Ages. The nearly completely preserved 14th-century town wall is the town\'s most important monument. The Ballenhaus, one of Bavaria\'s oldest trading houses, testifies to the town\'s medieval economic importance.',
    known_for: 'Romantic Road, medieval town wall, Lechtal valley',
    sights: ['Medieval town wall (nearly complete)', 'Ballenhaus (15th century)', 'Stadtpfarrkirche Mariä Himmelfahrt', 'Lech embankment and gorge', 'Romantic Road cycling route'],
    intro: 'From Schongau to Munich Airport it\'s approx. {km} km. Our taxi takes around {min} minutes to reach MUC.',
  },
  'taxi-fuerstenfeldbruck-flughafen-muenchen': {
    description: 'Fürstenfeldbruck is a town west of Munich known for the former Cistercian monastery Fürstenfeld and as part of the Munich commuter belt.',
    history: 'Fürstenfeld Monastery was founded in 1263 by Duke Ludwig II as atonement for the murder of his wife. The monastery church is a masterpiece of South German Baroque. The town became internationally known during the 1972 Olympics when the terrorist attack on the Israeli team ended tragically at the former airfield.',
    known_for: 'Fürstenfeld Monastery, 1972 Olympics tragedy, Amper Valley',
    sights: ['Fürstenfeld Monastery (Baroque church)', 'Amper riverside walks', 'Fürstenfeldbruck City Museum', 'Former airfield (now urban development area)', 'Bruck – Old Town on the Amper'],
    intro: 'From Fürstenfeldbruck to Munich Airport is approx. {km} km. Our taxi gets you to MUC in about {min} minutes.',
  },
  'taxi-germering-flughafen-muenchen': {
    description: 'Germering is the largest town in Fürstenfeldbruck district, west of Munich, and one of the fastest-growing municipalities in Bavaria.',
    history: 'Germering emerged in the 20th century through the merging of several villages and grew rapidly after World War II with the influx of expellees and Munich commuters. Today it is a modern residential town with excellent infrastructure and S-Bahn links to Munich.',
    known_for: 'Munich commuter belt, fast-growing municipality, S-Bahn access',
    sights: ['Germering Lake (recreation)', 'Stadtpark Germering', 'St.-Jakobus-Kirche', 'Wildpark Pasing (10 km)', 'Ammersee (20 km)'],
    intro: 'From Germering to Munich Airport the distance is approx. {km} km. Our taxi covers the route in around {min} minutes.',
  },
  'taxi-gauting-flughafen-muenchen': {
    description: 'Gauting is an affluent community in Starnberg district southwest of Munich, popular with commuters and known for its artists and intellectuals.',
    history: 'Gauting was first mentioned as a farming village in the Middle Ages and developed in the 19th century into a preferred residence for Munich citizens. Notable personalities such as Josef von Sternberg (film director) lived here. The village of Buchendorf is a popular destination in the Würm Valley.',
    known_for: 'Würm Valley, proximity to Lake Starnberg, Munich villa district',
    sights: ['Christuskirche Gauting (architecture)', 'Würm riverside walks', 'Lake Starnberg (10 km)', 'Buchendorf in the Würm Valley', 'Ammersee (25 km)'],
    intro: 'From Gauting to Munich Airport it\'s approx. {km} km. Our taxi brings you to MUC in about {min} minutes.',
  },
  'taxi-puchheim-flughafen-muenchen': {
    description: 'Puchheim is a municipality west of Munich in Fürstenfeldbruck district, strongly shaped by Munich commuters and well served by the S-Bahn.',
    history: 'Puchheim was a small farming village until the 20th century. The construction of the S4 S-Bahn line and the proximity to Munich turned it into a residential community for Munich commuters. Today Puchheim consists of the districts Puchheim-Bahnhof and Puchheim-Ort.',
    known_for: 'S-Bahn community, Munich commuters, western outskirts',
    sights: ['Puchheimer Weiher (recreation lake)', 'Altort Puchheim (historic village centre)', 'Germering Lake (5 km)', 'Fürstenfeld Monastery (8 km)', 'Ammersee (22 km)'],
    intro: 'From Puchheim to Munich Airport it\'s approx. {km} km. Our taxi covers the route in around {min} minutes.',
  },
  'taxi-unterschleissheim-flughafen-muenchen': {
    description: 'Unterschleißheim lies north of Munich directly on the A9 motorway, known as the location of BMW Group Vehicle Technology and as a rapidly growing community.',
    history: 'Unterschleißheim was a small village until the 1960s. Through the establishment of industry and BMW, and the construction of new residential areas, the municipality grew explosively. Today it is an important business location north of Munich.',
    known_for: 'BMW proximity, north Munich, lake recreation',
    sights: ['Unterschleißheim Gravel Lake (swimming)', 'BMW Group test facility', 'Heilig Kreuz settlement church', 'Schloss Unterschleißheim', 'Munich Airport (10 km)'],
    intro: 'From Unterschleißheim to Munich Airport is just {km} km. Our taxi reaches MUC in about {min} minutes.',
  },
  'taxi-garching-flughafen-muenchen': {
    description: 'Garching bei München is a science hub with a research reactor, TU Munich campus and several Max Planck Institutes, northeast of Munich.',
    history: 'Garching was a farming village until the 1950s. With the establishment of the TU Munich research reactor (1957) and numerous research institutions, Garching became a world-renowned science centre. Today more than 20,000 scientists and students work here.',
    known_for: 'TU Munich, research centre, science city',
    sights: ['FRM II Research Reactor (tours)', 'TU Munich Garching Campus', 'Hochbrück U-Bahn terminus (design)', 'Isar Valley (recreation)', 'Olympiapark Munich (20 km)'],
    intro: 'From Garching to Munich Airport it\'s approx. {km} km. Our taxi covers this route in about {min} minutes.',
  },
  'taxi-ismaning-flughafen-muenchen': {
    description: 'Ismaning lies northeast of Munich and is known as the home of several media companies, most notably Bayerischer Rundfunk (BR).',
    history: 'Ismaning has a history of over 1,000 years. Schloss Ismaning was a summer residence of the Munich prince-bishops. In the 20th century many media companies settled here. The Ismaning fish ponds are an important bird sanctuary.',
    known_for: 'Media hub, Schloss Ismaning, fish ponds nature reserve',
    sights: ['Schloss Ismaning (City Museum)', 'Ismaning Fish Ponds (nature reserve)', 'Bayerischer Rundfunk (BR) headquarters', 'Schloss gardens', 'Isar Valley (recreation)'],
    intro: 'From Ismaning to Munich Airport is approx. {km} km. Our taxi reaches MUC in about {min} minutes.',
  },
  'taxi-vaterstetten-flughafen-muenchen': {
    description: 'Vaterstetten is one of the largest municipalities in Ebersberg district in the eastern Munich commuter belt.',
    history: 'Vaterstetten emerged in the 20th century through the merging of several villages and grew rapidly after World War II with the influx of expellees. Today it is a modern residential community with a direct S-Bahn connection to Munich.',
    known_for: 'Eastern Munich outskirts, S-Bahn community, Ebersberg Forest',
    sights: ['Ebersberg Forest (nearby)', 'Schönau am Ebersberger Forst', 'Parksee Vaterstetten', 'Heilig Kreuz Parish Church', 'Ebersberg (10 km)'],
    intro: 'From Vaterstetten to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-gilching-flughafen-muenchen': {
    description: 'Gilching is a municipality in Starnberg district, known as the headquarters of Webasto and as a green residential community in the Würm Valley.',
    history: 'Gilching was a small farming village that developed into a residential community for Munich commuters in the 20th century. Webasto (automotive supplier) is headquartered here and is the region\'s largest employer.',
    known_for: 'Webasto, Würm Valley, lake landscape',
    sights: ['Ammersee (15 km)', 'Lake Starnberg (18 km)', 'Würm Valley cycling route', 'Webasto headquarters', 'Seefeld am Pilsensee (10 km)'],
    intro: 'From Gilching to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-olching-flughafen-muenchen': {
    description: 'Olching lies in the Amper Valley west of Munich and is one of the fastest-growing municipalities in Fürstenfeldbruck district.',
    history: 'Olching has an early medieval history and became a residential community for Munich commuters through the railway and later the S-Bahn. The Amper and surrounding floodplain forests are important recreational areas.',
    known_for: 'Amper Valley, fast-growing community, S-Bahn west of Munich',
    sights: ['Amper floodplain forests (nature reserve)', 'Olchinger See (swimming lake)', 'Olching City Museum', 'Fürstenfeld Monastery (8 km)', 'Gernlinden Moor (nature reserve)'],
    intro: 'From Olching to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-grafing-flughafen-muenchen': {
    description: 'Grafing bei München is a small town in Ebersberg district east of Munich with a historic old town and S-Bahn connection.',
    history: 'Grafing received its town charter in the 14th century and was an important market town on the way to Salzburg. The well-preserved old town with its town tower and historic buildings is a local landmark.',
    known_for: 'Historic old town, Grafing Lake, eastern Munich outskirts',
    sights: ['Grafing Town Tower', 'Historic Old Town', 'Grafinger See (swimming lake)', 'St. Ägidius Parish Church', 'Ebersberg Forest (10 km)'],
    intro: 'From Grafing to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-kirchheim-bei-muenchen-flughafen-muenchen': {
    description: 'Kirchheim bei München lies immediately east of the state capital and is one of the most densely populated and fastest-growing municipalities in Munich district.',
    history: 'Kirchheim was greatly expanded in the 20th century through new housing developments. Its convenient location near the A94 motorway and a direct S-Bahn connection to Munich makes it popular with families and commuters. The trade fair city of Riem (Messestadt Riem) is nearby.',
    known_for: 'Messestadt proximity, eastern Munich outskirts, Riemer Park',
    sights: ['Riemer Park (former Expo site)', 'Messestadt Riem (10 min)', 'Heimstettener See (swimming lake)', 'St. Nikolaus Parish Church', 'Munich Airport (12 km)'],
    intro: 'From Kirchheim bei München to Munich Airport it\'s just {km} km. Our taxi reaches MUC in about {min} minutes.',
  },
  'taxi-haar-flughafen-muenchen': {
    description: 'Haar is an eastern Munich suburb known as the location of the Isar-Amper-Klinikum and as a well-connected residential town on the S-Bahn.',
    history: 'Haar developed into a residential community in the 20th century. The Isar-Amper-Klinikum (former mental health institution) has been the defining building for over 100 years. Today Haar is densely built and well connected to Munich.',
    known_for: 'Clinic location, eastern Munich suburbs, S-Bahn access',
    sights: ['Isar-Amper-Klinikum park grounds', 'Town centre with parish church', 'Riemer Park (8 km)', 'Egglburger See (12 km)', 'Munich East (15 min by S-Bahn)'],
    intro: 'From Haar to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-holzkirchen-flughafen-muenchen': {
    description: 'Holzkirchen is a market town southeast of Munich in the Alpine foothills, known for the Holzkirchner Bockbierfest and a strong brewing tradition.',
    history: 'Holzkirchen was founded as a market in the 12th century and was an important stopover on the route to South Tyrol. The Holzkirchner Brauhaus brewing tradition is over 500 years old. Today Holzkirchen is an economically strong regional centre.',
    known_for: 'Bockbierfest, brewing tradition, Alpine foothills',
    sights: ['Holzkirchner Bockbierfest (annual)', 'St. Laurentius Parish Church', 'Mangfall flood plains (nature)', 'Hausham Mining Museum (15 km)', 'Tegernsee (25 km)'],
    intro: 'From Holzkirchen to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-tutzing-flughafen-muenchen': {
    description: 'Tutzing on Lake Starnberg is a picturesque community with a castle, known as the venue of the Evangelical Academy Tutzing and a popular destination.',
    history: 'Schloss Tutzing was once a summer residence of the aristocracy. In the 19th century Munich citizens discovered Tutzing as a day-trip destination. The Evangelical Academy Tutzing (since 1947) is an important forum for social and political debate.',
    known_for: 'Lake Starnberg, Evangelical Academy, lake views',
    sights: ['Schloss Tutzing (Evangelical Academy)', 'Lake Starnberg promenade', 'St. Joseph Parish Church', 'Buchberg near Tutzing (viewpoint)', 'Tutzing Sailing Club'],
    intro: 'From Tutzing to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-penzberg-flughafen-muenchen': {
    description: 'Penzberg is a former mining town at the foot of the Bavarian Alps, now known as the location of Roche – one of Europe\'s largest pharmaceutical companies.',
    history: 'Penzberg was a coal-mining location for over 100 years (1871–1966). After the mine closed, the economy diversified and Roche built a major production centre here. Today over 9,000 people work at the Roche Penzberg site.',
    known_for: 'Roche pharmaceutical company, mining history, Alpine foothills',
    sights: ['Museum Penzberg (town history & mining)', 'Roche campus buildings (architecture)', 'Loisach riverside', 'Icking (Isar Valley, 18 km)', 'Kochelsee (20 km)'],
    intro: 'From Penzberg to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-murnau-flughafen-muenchen': {
    description: 'Murnau am Staffelsee is a traditional Bavarian market town known as the former meeting place of the "Der Blaue Reiter" (Blue Rider) art movement and for its views of the Zugspitze.',
    history: 'Murnau was an important location for the "Der Blaue Reiter" art movement at the start of the 20th century. Wassily Kandinsky and Gabriele Münter lived here and created some of their most important works. The Staffelsee, surrounded by moors, inspired many artists.',
    known_for: 'Blue Rider art movement, Staffelsee, Alpine views',
    sights: ['Schlossmuseum Murnau (Blue Rider)', 'Gabriele Münter House', 'Staffelsee – beaches and boat hire', 'Murnauer Moos nature reserve', 'Wetterstein mountains panorama'],
    intro: 'From Murnau to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-garmisch-partenkirchen-flughafen-muenchen': {
    description: 'Garmisch-Partenkirchen is Germany\'s most famous winter sports resort at the foot of the Zugspitze (2,962 m) and host of the 1936 Winter Olympics.',
    history: 'The two formerly separate villages of Garmisch and Partenkirchen were merged in 1935. The 1936 Winter Olympics left numerous sports facilities. The Zugspitze, Germany\'s highest peak, makes the region Germany\'s most popular winter sports destination. Composer Richard Strauss lived and died here.',
    known_for: 'Zugspitze, winter sports, 1936 Olympics',
    sights: ['Zugspitze (2,962 m) with cable car', 'Partnach Gorge', 'Richard Strauss Institute', 'Olympic Ski Stadium', 'Wank mountain (cable car, Alpine views)'],
    intro: 'From Garmisch-Partenkirchen to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-bad-reichenhall-flughafen-muenchen': {
    description: 'Bad Reichenhall is a traditional saline spa resort in the Berchtesgadener Land near the Austrian border, with salt extraction going back 2,500 years.',
    history: 'Salt shaped Bad Reichenhall for 2,500 years. The historic salines (graduation towers) are preserved as a technical monument. Bad Reichenhall was a favourite spa resort of the European aristocracy in the 19th century.',
    known_for: 'Salt spa resort, graduation towers, Berchtesgadener Land',
    sights: ['Old Saline and Salt Museum', 'Graduation towers (brine inhalation)', 'Predigtstuhl cable car (1,614 m)', 'Kurgarten and Kurhaus', 'St. Zeno Collegiate Church'],
    intro: 'From Bad Reichenhall to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-berchtesgaden-flughafen-muenchen': {
    description: 'Berchtesgaden is a historic mountain market town in Berchtesgaden National Park, world-famous for the Königssee and the history of the Nazi regime.',
    history: 'The Augustinian Canons\' Foundation (est. 1102) was the political centre of the region for centuries. In the 20th century Berchtesgaden became internationally known through Hitler\'s "Berghof" mountain retreat on the Obersalzberg. Today it is a popular tourist destination with national park and Königssee.',
    known_for: 'Königssee, National Park, Obersalzberg',
    sights: ['Königssee with boat trips', 'Berchtesgaden Salt Mine', 'Obersalzberg Documentation Centre', 'Kehlsteinhaus ("Eagle\'s Nest")', 'Berchtesgaden National Park'],
    intro: 'From Berchtesgaden to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-traunstein-flughafen-muenchen': {
    description: 'Traunstein is the district town of the same-named district in Chiemgau, known as the birthplace of Pope Benedict XVI and for the traditional Georgiritt procession.',
    history: 'Traunstein was founded as a salt town in 1245. Pope Benedict XVI (Joseph Ratzinger) has strong roots in this region. The Georgiritt on Easter Monday is one of Germany\'s most famous horse-blessing processions.',
    known_for: 'Pope Benedict XVI, Georgiritt, Chiemgau',
    sights: ['St. Oswald Parish Church', 'Town tower and old town', 'Rathausplatz', 'Chiemgauarena (sports)', 'Chiemsee (25 km)'],
    intro: 'From Traunstein to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-prien-am-chiemsee-flughafen-muenchen': {
    description: 'Prien am Chiemsee is the gateway to Lake Chiemsee – the "Bavarian Sea". Steamboats depart from here to Herreninsel with Schloss Herrenchiemsee.',
    history: 'Prien has been an important market town since the Middle Ages. Lake Chiemsee and its islands became famous in the 19th century through King Ludwig II, who built a Hall of Mirrors palace on Herreninsel modelled on Versailles.',
    known_for: 'Chiemsee, Schloss Herrenchiemsee, King Ludwig II',
    sights: ['Schloss Herrenchiemsee (King Ludwig II)', 'Steamboat trips on Chiemsee', 'Frauenchiemsee Monastery (Ladies\' Island)', 'Chiemsee lakeside promenade Prien', 'Kampenwand (cable car, 1,669 m)'],
    intro: 'From Prien am Chiemsee to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-landshut-flughafen-muenchen': {
    description: 'Landshut is the capital of Lower Bavaria, famous for the world\'s tallest brick church tower (St. Martin), Burg Trausnitz castle, and the historic Landshut Wedding festival.',
    history: 'Landshut was founded in 1204 by Duke Ludwig I and was the residence of the Lower Bavarian Wittelsbacher dynasty in the Middle Ages. The Landshut Wedding of 1475 was the most magnificent wedding feast of the Middle Ages and has been re-enacted every four years since 1903.',
    known_for: 'Landshut Wedding, St. Martin Church, Lower Bavarian capital',
    sights: ['St. Martin Church (world\'s tallest brick tower)', 'Burg Trausnitz', 'Landshut Old Town and Residenz', 'Stadtresidenz (Italian Renaissance palace)', 'Isar riverside promenade'],
    intro: 'From Landshut to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-straubing-flughafen-muenchen': {
    description: 'Straubing is a Lower Bavarian city on the Danube, known for the Gäubodenvolksfest (Bavaria\'s second-largest folk festival) and its historic town tower.',
    history: 'Straubing has Roman roots (Sorviodurum) and was a ducal residence town in the Middle Ages. Agnes Bernauer, a barber\'s daughter, was drowned in the Danube in 1435 on the orders of the duke. The Gäubodenvolksfest draws over one million visitors annually.',
    known_for: 'Gäubodenvolksfest, town tower, Danube riverside',
    sights: ['Straubing Town Tower', 'Ducal Palace', 'Roman Museum (Roman cavalry armour)', 'St. Jakob\'s Church', 'Agnes Bernauer Memorial'],
    intro: 'From Straubing to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-passau-flughafen-muenchen': {
    description: 'Passau is the "City of Three Rivers" – where the Danube, Inn and Ilz meet – with a Baroque old town and the Cathedral of St. Stephen, home to the world\'s largest cathedral organ.',
    history: 'Passau was for centuries one of the most powerful cities in Bavaria as an episcopal residence and trading hub. The Bishopric of Passau once extended all the way to Vienna. The Baroque old town on the peninsula between the Danube and Inn is one of the most beautiful in Europe.',
    known_for: 'City of Three Rivers, cathedral organ, Baroque old town',
    sights: ['St. Stephen\'s Cathedral (world\'s largest cathedral organ)', 'Veste Oberhaus (City Museum)', 'Three-Rivers Corner (Danube, Inn, Ilz)', 'Old Town with Town Hall Square', 'Glass Museum Passau'],
    intro: 'From Passau to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-regensburg-flughafen-muenchen': {
    description: 'Regensburg is the capital of the Upper Palatinate with a UNESCO World Heritage old town and is one of the best-preserved medieval cities in Europe.',
    history: 'The Roman fortress Castra Regina (179 AD) was the main base of the Danube legion. In the Middle Ages Regensburg was the largest city north of the Alps and a venue for Imperial Diets. The Cathedral of St. Peter, the Stone Bridge (1146) and the medieval cityscape make Regensburg a UNESCO World Heritage Site.',
    known_for: 'UNESCO old town, Stone Bridge, medieval heritage',
    sights: ['Stone Bridge (1146)', 'St. Peter\'s Cathedral (Gothic)', 'UNESCO World Heritage Old Town', 'Walhalla (15 km, marble temple)', 'BMW Plant Regensburg'],
    intro: 'From Regensburg to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-nuernberg-flughafen-muenchen': {
    description: 'Nuremberg is Bavaria\'s second-largest city, famous for its historic old town, the world-renowned Christkindlesmarkt Christmas market, and the Nuremberg Trials.',
    history: 'Nuremberg was one of the most important cities of the Holy Roman Empire as a Free Imperial City in the Middle Ages. Albrecht Dürer, the most important German painter of the Renaissance, was born here. In the 20th century Nuremberg was the scene of Nazi Party rallies and the war crimes trials.',
    known_for: 'Christkindlesmarkt, Imperial Castle, Nuremberg Trials, Dürer',
    sights: ['Nuremberg Imperial Castle', 'Christkindlesmarkt (Advent)', 'Germanic National Museum', 'Documentation Centre Nazi Party Rally Grounds', 'Albrecht Dürer House'],
    intro: 'From Nuremberg to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-kempten-flughafen-muenchen': {
    description: 'Kempten in the Allgäu is one of Germany\'s oldest cities, known as the economic centre of the Allgäu region and for its Roman excavation sites.',
    history: 'Kempten (Cambodunum) is one of the oldest cities north of the Alps. As a Roman provincial capital it was more significant than Augsburg. In the Middle Ages Kempten was ruled by a wealthy abbey. The double city structure (abbey town and free imperial city) is unique in Germany.',
    known_for: 'Germany\'s oldest city, Roman archaeological park, Allgäu',
    sights: ['Cambodunum Archaeological Park (Roman)', 'St. Lorenz Basilica (Baroque)', 'Kempten Residenz', 'Allgäu Museum', 'Burghalde (city park)'],
    intro: 'From Kempten to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  // Austria
  'taxi-salzburg-flughafen-muenchen': {
    description: 'Salzburg is the city of Mozart – birthplace of the composer and a UNESCO World Heritage city on the Salzach with a Baroque old town and Hohensalzburg Fortress.',
    history: 'Salzburg was for centuries an independent prince-archbishopric made wealthy by the salt trade. Wolfgang Amadeus Mozart was born here in 1756. The Salzburg Festival (since 1920) has made it an international cultural metropolis. The Baroque old town has been a UNESCO World Heritage Site since 1997.',
    known_for: 'Mozart, Salzburg Festival, UNESCO old town, Salzach River',
    sights: ['Hohensalzburg Fortress', 'Mozart\'s Birthplace', 'Salzburg Cathedral', 'Mirabell Gardens', 'Salzburg Festival (summer)'],
    intro: 'From Salzburg to Munich Airport it\'s approx. {km} km across the border. Our taxi covers the route in about {min} minutes at a fixed price.',
  },
  'taxi-innsbruck-flughafen-muenchen': {
    description: 'Innsbruck is the capital of Tyrol, twice Olympic host city (1964, 1976) and lies in the heart of the Alps at the confluence of the Inn and Sill rivers.',
    history: 'Innsbruck was one of the most significant cities of the Holy Roman Empire as a Habsburg residence. Emperor Maximilian I (1459–1519) made it his imperial seat. The Golden Roof (1496) is the most famous landmark. The 1964 and 1976 Winter Olympics shaped its modern development.',
    known_for: 'Golden Roof, Olympics, Tyrolean Alps, Habsburgs',
    sights: ['Golden Roof (15th century)', 'Hofburg Innsbruck', 'Bergisel Ski Jump', 'Nordkette cable car (city views)', 'Triumphal Arch'],
    intro: 'From Innsbruck to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes across the Austrian border.',
  },
  'taxi-kufstein-flughafen-muenchen': {
    description: 'Kufstein is a border town on the Inn between Bavaria and Tyrol, known for its impressive fortress and as the gateway to the Tyrolean Alps.',
    history: 'Kufstein was an important border fortress and changed hands several times between Bavaria and Austria. The Kufstein Fortress (13th century) is one of the best-preserved castle complexes in the Alps.',
    known_for: 'Kufstein Fortress, Heldenorgel, Inn border town, Tyrolean Alps',
    sights: ['Kufstein Fortress', 'Heldenorgel (world\'s largest open-air organ)', 'Inn riverside promenade', 'Kufsteinerland mountain railways', 'Kaisergebirge (Kaiser via ferrata)'],
    intro: 'From Kufstein to Munich Airport it\'s approx. {km} km across the Austrian border. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-woergl-flughafen-muenchen': {
    description: 'Wörgl is a Tyrolean railway junction town in the Inn Valley, known worldwide for the "Wörgl Experiment" of 1932 – a local currency circulation model.',
    history: 'Wörgl gained worldwide fame for the Freigeld (free money) experiment (1932/33), in which Mayor Michael Unterguggenberger fought unemployment during the Great Depression. As an important rail junction, Wörgl connects the Inn Valley with the Zillertal and the Brixental.',
    known_for: 'Wörgl Experiment, Inn Valley rail junction, Tyrolean lowlands',
    sights: ['Freigeld Experiment Memorial Museum', 'Wörgl Parish Church', 'Inn floodplains (recreation)', 'Brixental (Kitzbühel Alps, 15 km)', 'Zahmer Kaiser (hiking area)'],
    intro: 'From Wörgl to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-kitzbuehl-flughafen-muenchen': {
    description: 'Kitzbühel is one of the most exclusive winter sports and luxury resorts in the Alps, world-famous for the Hahnenkamm races and as a summer retreat.',
    history: 'Kitzbühel became wealthy in the Middle Ages through silver and copper mining. In the 19th century wealthy Munich and Vienna residents discovered it as a summer retreat. The Hahnenkamm races (annually in January) are the most demanding downhill race in the World Cup circuit.',
    known_for: 'Hahnenkamm races, luxury ski resort, Tyrolean Alps',
    sights: ['Hahnenkamm cable car', 'Streif (Hahnenkamm downhill)', 'Kitzbühel medieval old town', 'Kitzbüheler Horn', 'Hintersteiner See'],
    intro: 'From Kitzbühel to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-bregenz-flughafen-muenchen': {
    description: 'Bregenz is the capital of Vorarlberg on Lake Constance, world-famous for the Bregenz Festival with its spectacular floating stage – the world\'s largest open-air stage.',
    history: 'Brigantium was an important Roman military base on Lake Constance. The Bregenz Festival (since 1946) has made the city an international cultural centre. The Vorarlberg Museum tells 30,000 years of regional history.',
    known_for: 'Bregenz Festival, Lake Constance, floating stage',
    sights: ['Bregenz Festival floating stage', 'Pfänder (cable car, 1,064 m)', 'Vorarlberg Museum', 'Upper Old Town', 'Lake Constance promenade'],
    intro: 'From Bregenz to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-rosenheim-austria-flughafen-muenchen': {
    description: 'St. Johann in Tirol is a popular Tyrolean holiday resort in the Kitzbühel Alps, a starting point for summer and winter visitors.',
    history: 'St. Johann in Tirol received market rights in the 14th century and was an important transit trade hub through the Inn Valley. The landmark is the Baroque Parish Church of the Assumption (1728). The village developed into a tourism centre in the 20th century.',
    known_for: 'Kitzbühel Alps, summer and winter tourism, Inn Valley',
    sights: ['Assumption Parish Church (Baroque)', 'Kitzbühel Alps hiking trails', 'St. Johann ski area', 'Pillersee (recreation)', 'Wilder Kaiser (mountain massif)'],
    intro: 'From St. Johann in Tirol to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-zell-am-see-flughafen-muenchen': {
    description: 'Zell am See is a Tyrolean tourism centre on the lake of the same name in the Pinzgau, a year-round popular ski and hiking area with the Kitzsteinhorn glacier.',
    history: 'Zell am See developed from a fishing village into a tourist destination in the 19th century after the Tauern railway (1909) opened up the area. The Kitzsteinhorn glacier (3,203 m) makes it a year-round ski destination.',
    known_for: 'Kitzsteinhorn, glacier skiing, Zeller See',
    sights: ['Kitzsteinhorn Glacier (summer skiing)', 'Zeller See (lakeside beach)', 'Schmittenhöhe (cable car)', 'Zell am See Old Town', 'Kaprun power station (tours)'],
    intro: 'From Zell am See to Munich Airport it\'s approx. {km} km across the Austrian border. Our taxi covers the route in about {min} minutes.',
  },
  // Switzerland
  'taxi-zuerich-flughafen-muenchen': {
    description: 'Zurich is Switzerland\'s largest city and its financial and economic centre, situated on Lake Zurich with direct views of the Alps.',
    history: 'Turicum was a Roman toll post. Zurich became an important trading city in the Middle Ages. The Reformation under Huldrych Zwingli (1519) began in Zurich. Today it is one of the world\'s most important financial centres and regularly ranks among the most liveable cities.',
    known_for: 'Financial centre, old town, Lake Zurich, Grossmünster',
    sights: ['Old Town (Niederdorf)', 'Kunsthaus Zurich', 'Grossmünster and Fraumünster', 'Uetliberg (viewpoint)', 'Lake Zurich boat trips'],
    intro: 'From Zurich to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes with a fixed price.',
  },
  'taxi-bern-flughafen-muenchen': {
    description: 'Bern is the federal city of Switzerland with one of the best-preserved medieval city centres in Europe, listed as a UNESCO World Heritage Site.',
    history: 'Bern was founded in 1191 by Duke Berthold V of Zähringen. Since 1848 it has been the seat of Switzerland\'s federal authorities. Albert Einstein lived and worked here (Kramgasse house) when he developed the theory of relativity in 1905.',
    known_for: 'Federal city, UNESCO old town, Einstein, Zytglogge',
    sights: ['UNESCO World Heritage Old Town', 'Zytglogge (clock tower)', 'Bern Minster', 'Bear Park (heraldic animal)', 'Zentrum Paul Klee'],
    intro: 'From Bern to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes with a fixed price.',
  },
  'taxi-basel-flughafen-muenchen': {
    description: 'Basel is Switzerland\'s cultural capital, known as the host city of Art Basel (the world\'s largest art fair) and for the pharmaceutical industry (Novartis, Roche).',
    history: 'Basel was important as a bishop\'s seat and trading place on the Rhine since the Middle Ages. The University of Basel (1460) is the oldest in Switzerland. Erasmus of Rotterdam taught here. Today Basel is home to the world\'s most important art fair, Art Basel.',
    known_for: 'Art Basel, art, pharmaceutical hub, Three-Country Corner',
    sights: ['Basel Minster', 'Kunstmuseum Basel (largest art collection in Switzerland)', 'Art Basel (art fair, June)', 'Fondation Beyeler', 'Middle Rhine Bridge and Rhine embankment'],
    intro: 'From Basel to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes with a fixed price.',
  },
  'taxi-st-gallen-flughafen-muenchen': {
    description: 'St. Gallen is the economic centre of eastern Switzerland, known for the UNESCO World Heritage Abbey Library and the traditional embroidery trade.',
    history: 'The Abbey of St. Gallen (founded 612) was one of the most important cultural centres in medieval Europe. The Abbey Library contains over 170,000 books including priceless medieval manuscripts. In the 19th century St. Gallen was the world leader in lace and embroidery production.',
    known_for: 'Abbey Library, embroidery, UNESCO cultural heritage',
    sights: ['St. Gallen Abbey Library (UNESCO)', 'St. Gallen Cathedral', 'Textile Museum', 'City Park', 'Lake Constance (20 km)'],
    intro: 'From St. Gallen to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-konstanz-flughafen-muenchen': {
    description: 'Constance lies on Lake Constance (Germany/Switzerland border) and is the largest city on the lake, known for the Council of Constance (1414–1418) and its university.',
    history: 'The Council of Constance (1414–1418) was the most important church assembly of the Middle Ages – Jan Hus was burned here and the Church Schism ended. In World War II Constance remained unscathed because it kept its lights on and Allied bombers mistook it for a Swiss town.',
    known_for: 'Council of Constance, Lake Constance, border city',
    sights: ['Concilium Building', 'Constance Minster', 'Lake Constance promenade', 'Imperia sculpture in the harbour', 'Mainau Island (flower island, 8 km)'],
    intro: 'From Constance to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-lindau-flughafen-muenchen': {
    description: 'Lindau is on an island in Lake Constance and is a picturesque town with a medieval old town, known for the Nobel Laureate Meetings.',
    history: 'Lindau was an important trading place on Lake Constance as a Free Imperial City. The old town island is connected to the mainland by a bridge and a railway. Since 1951 Nobel Laureates have met annually in Lindau – a unique scientific forum.',
    known_for: 'Lake Constance island, Nobel Laureate Meetings, old town',
    sights: ['Old town island with medieval streetscape', 'Mangturm and Bavarian Lion (harbour entrance)', 'St. Peter\'s Church with Hans Holbein murals', 'Lake Constance promenade', 'Nobel Laureate Meetings (June/July)'],
    intro: 'From Lindau to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-friedrichshafen-flughafen-muenchen': {
    description: 'Friedrichshafen on Lake Constance is home to Zeppelin, Airbus, Dornier and the Messe Friedrichshafen trade fair – an important industrial and technology hub.',
    history: 'Count Ferdinand von Zeppelin built the first rigid airship (LZ 1) here in 1900. Heavily destroyed in World War II, Friedrichshafen became a modern industrial location with companies like ZF, Airbus and MTU.',
    known_for: 'Zeppelin, airship construction, ZF Friedrichshafen, Lake Constance',
    sights: ['Zeppelin Museum Friedrichshafen', 'Zeppelin works (successor company)', 'Lake Constance promenade', 'Messe Friedrichshafen', 'Schloss Friedrichshafen'],
    intro: 'From Friedrichshafen to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-ulm-flughafen-muenchen': {
    description: 'Ulm is the birthplace of Albert Einstein and home to Ulm Minster with the world\'s tallest church tower (161.53 m).',
    history: 'Ulm was an important Free Imperial City and trading metropolis in the Middle Ages. Albert Einstein was born in Ulm in 1879. Ulm Minster (foundation laid 1377) was not completed until 1890.',
    known_for: 'Ulm Minster, Einstein, Danube riverside',
    sights: ['Ulm Minster (world\'s tallest church tower, 161 m)', 'Fishermen\'s Quarter (old town)', 'Albert Einstein Birthplace (commemorative plaque)', 'City walls and Butchers\' Tower', 'Ulm Museum'],
    intro: 'From Ulm to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-chur-flughafen-muenchen': {
    description: 'Chur is Switzerland\'s oldest city (settled c. 3000 BC) and the capital of Graubünden, an important hub for the Rhaetian Railway and the Glacier Express.',
    history: 'Chur is one of the oldest continuously inhabited cities in Europe. The Romans called it Curia Raetorum. The bishop\'s foundation (5th century) shaped its medieval history. Today Chur is an important tourism hub for Graubünden as the starting point of the Glacier Express.',
    known_for: 'Switzerland\'s oldest city, Glacier Express, Graubünden',
    sights: ['Chur Cathedral (Romanesque-Gothic)', 'Episcopal Court', 'Rhaetian Museum', 'Old Town with narrow lanes', 'Glacier Express departure station'],
    intro: 'From Chur to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-davos-flughafen-muenchen': {
    description: 'Davos is the world\'s most famous mountain village – host of the World Economic Forum (WEF) and a winter sports resort on Europe\'s highest plateau.',
    history: 'Davos developed in the 19th century as a sanatorium for tuberculosis patients (high altitude, clean air). Writer Thomas Mann described Davos in his novel "The Magic Mountain" (1924). Since 1971 the World Economic Forum (WEF) has been a defining annual highlight.',
    known_for: 'World Economic Forum, Parsenn ski area, The Magic Mountain',
    sights: ['Jakobshorn ski area', 'Parsenn (world\'s largest ski area)', 'Kirchner Museum Davos', 'Davos Lake', 'WEF Congress Centre'],
    intro: 'From Davos to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes with a fixed price.',
  },
  'taxi-luzern-flughafen-muenchen': {
    description: 'Lucerne is one of Switzerland\'s most visited cities, known for the Chapel Bridge (Europe\'s oldest covered wooden bridge), Lake Lucerne and its Alpine backdrop.',
    history: 'Lucerne was important in the Middle Ages as a market town and transit point on the route to Italy. The Chapel Bridge (1333) is the city\'s landmark. The Lion Monument (1821), a lion carved in rock, commemorates the Swiss Guards who fell in Paris.',
    known_for: 'Chapel Bridge, Lake Lucerne, Rigi, Heart of Switzerland',
    sights: ['Chapel Bridge and Water Tower', 'Lion Monument', 'Rigi (Queen of the Mountains, cog railway)', 'Swiss Museum of Transport', 'Lake Lucerne boat trips'],
    intro: 'From Lucerne to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes with a fixed price.',
  },
  'taxi-winterthur-flughafen-muenchen': {
    description: 'Winterthur is Switzerland\'s sixth-largest city, known for its significant museums (Kunstmuseum, Photo Museum) and as a former industrial city (Sulzer, Rieter).',
    history: 'Winterthur was one of Europe\'s most important industrial centres in the 19th century with engineering companies such as Sulzer and Rieter. The wealthy industrialists promoted art and culture – creating one of Switzerland\'s most important art collections.',
    known_for: 'Museum city, industrial history, Sulzer',
    sights: ['Kunstmuseum Winterthur', 'Fotomuseum Winterthur', 'Technorama (Science Centre)', 'Winterthur Old Town', 'Kyburg Castle (15 km)'],
    intro: 'From Winterthur to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  // Bavaria – additional
  'taxi-muenchen-flughafen-muenchen': {
    description: 'Munich is the state capital of Bavaria and Germany\'s third-largest city – a world city with heart, home of Oktoberfest and FC Bayern Munich.',
    history: 'Henry the Lion founded Munich in 1158 on the Isar River. In the 19th century it became a magnificent royal capital under King Ludwig I. The Hofbräuhaus, Frauenkirche and the Pinakotheken museums are world-famous. Munich is today a global centre for technology, media and the arts.',
    known_for: 'Oktoberfest, FC Bayern, Residenz, world-class city',
    sights: ['Marienplatz & Neues Rathaus', 'English Garden', 'Frauenkirche', 'Deutsches Museum', 'Olympiapark'],
    intro: 'From Munich city centre to Munich Airport (MUC) it\'s approx. {km} km along the A9 or A92. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-pfaffenhofen-flughafen-muenchen': {
    description: 'Pfaffenhofen an der Ilm is a growing district town north of Munich with a historic old town and a thriving pharmaceutical industry.',
    history: 'Pfaffenhofen received its town charter in 1438 and was an important market town on the Ilm. Today pharmaceutical companies such as Dr. Pfleger are a significant economic factor.',
    known_for: 'Pharmaceutical hub, Ilm Valley, north of Munich',
    sights: ['Main square with historic townhouses', 'Town tower', 'St. John\'s Parish Church', 'Ilm riverside promenade', 'City Museum'],
    intro: 'From Pfaffenhofen to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-aichach-flughafen-muenchen': {
    description: 'Aichach is the district town of Aichach-Friedberg district in the Wittelsbacher Land, west of Munich.',
    history: 'Aichach was the ancestral seat of the Wittelsbacher dynasty and received its town charter in the 13th century. The hilltop Frauenkirche is an important Gothic building.',
    known_for: 'Wittelsbacher Land, historic district town, Paar Valley',
    sights: ['Mariä Himmelfahrt Parish Church', 'Aichach City Museum', 'Paar Valley cycling route', 'Wittelsbacher Land', 'Friedberg (neighbouring town, 10 km)'],
    intro: 'From Aichach to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-neuburg-an-der-donau-flughafen-muenchen': {
    description: 'Neuburg an der Donau is a historic residence city on the Danube, seat of the Palatine-Neuburg ducal house in the 16th century.',
    history: 'Duke Ottheinrich developed Neuburg into a Renaissance residence in the 16th century. Neuburg Palace is one of the most significant Renaissance castles in southern Germany.',
    known_for: 'Renaissance palace, Danube city, Palatine-Neuburg',
    sights: ['Neuburg Palace (Renaissance)', 'Hofkirche Neuburg', 'City Museum', 'Danube riverside promenade', 'Brandl Garden'],
    intro: 'From Neuburg an der Donau to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-muehldorf-am-inn-flughafen-muenchen': {
    description: 'Mühldorf am Inn is a district town east of Munich with a historic main square and a significant role in chemical and fibreglass production.',
    history: 'Mühldorf received its town charter in the 13th century and was an important Inn crossing point. The elongated main square with the Nagelschmiedturm is a distinctive feature of the town.',
    known_for: 'Inn Valley, historic main square, chemical industry hub',
    sights: ['Main square with Nagelschmiedturm', 'Inn riverside promenade', 'City Museum', 'Town Hall', 'Inn cycling route'],
    intro: 'From Mühldorf am Inn to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-eichstaett-flughafen-muenchen': {
    description: 'Eichstätt is a Baroque city in the Altmühl Valley with an episcopal residence and university, known for fossils including the Archaeopteryx.',
    history: 'The Bishopric of Eichstätt was founded in 741. The city was magnificently rebuilt in Baroque style after the Thirty Years\' War. The Solnhofen quarry near Eichstätt has yielded world-famous fossils including the Archaeopteryx.',
    known_for: 'Baroque city, Archaeopteryx, Altmühl Valley, Episcopal residences',
    sights: ['Eichstätt Cathedral', 'Willibaldsburg castle', 'Jura Museum (Archaeopteryx)', 'Altmühl Valley Nature Park', 'Residenzplatz'],
    intro: 'From Eichstätt to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-kelheim-flughafen-muenchen': {
    description: 'Kelheim lies at the confluence of the Altmühl and Danube, known for the Liberation Hall and the Danube Gorge – one of Bavaria\'s most beautiful river landscapes.',
    history: 'Kelheim was a Celtic settlement and Roman fort. The Liberation Hall on Michelsberg was built by King Ludwig I to commemorate the liberation wars against Napoleon (1842–1863). The Danube Gorge between Kelheim and Weltenburg is a natural wonder.',
    known_for: 'Liberation Hall, Danube Gorge, Weltenburg Monastery',
    sights: ['Liberation Hall (King Ludwig I)', 'Danube Gorge (boat trip)', 'Weltenburg Monastery (oldest monastery brewery)', 'Altmühl Valley panoramic trail', 'Kelheim town walls'],
    intro: 'From Kelheim to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-dingolfing-flughafen-muenchen': {
    description: 'Dingolfing is the centre of its eponymous district in Lower Bavaria and world-famous as the location of BMW\'s largest plant (Plant 2.4) in the world.',
    history: 'Dingolfing received its town charter in the 13th century. The BMW plant opened in 1973 and today produces over 400,000 vehicles per year – BMW\'s largest single plant worldwide.',
    known_for: 'BMW main plant, Isar River, Lower Bavaria',
    sights: ['BMW Plant Dingolfing (tours)', 'Herzogsburg (City Museum)', 'St. John\'s Parish Church', 'Isar Valley', 'Lower Bavarian golf region'],
    intro: 'From Dingolfing to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-altoetting-flughafen-muenchen': {
    description: 'Altötting is Germany\'s most important Marian pilgrimage site and Bavaria\'s spiritual heart – over one million pilgrims visit the Chapel of Grace annually.',
    history: 'The Chapel of Grace in Altötting houses a Black Madonna from the 14th century. Altötting was a Wittelsbach residence and houses the Heart Crypt with the hearts of the Bavarian kings. Both Pope John Paul II and Pope Benedict XVI visited the pilgrimage site.',
    known_for: 'Marian pilgrimage, Chapel of Grace, Bavaria\'s spiritual heart',
    sights: ['Chapel of Grace with Black Madonna', 'St. Philip and Jakob Collegiate Church', 'Jerusalem Panorama', 'Wittelsbach Heart Crypt', 'Capuchin Monastery'],
    intro: 'From Altötting to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-wasserburg-am-inn-flughafen-muenchen': {
    description: 'Wasserburg am Inn sits on an Inn peninsula and is regarded as one of Bavaria\'s most beautiful medieval towns – a living open-air museum.',
    history: 'Wasserburg emerged as a trading town on the Inn and was enriched by the salt trade. Its unique location on an Inn peninsula made it a natural fortress. The Gothic old town with its arcaded houses is exceptionally well preserved.',
    known_for: 'Medieval Inn peninsula town, salt trade, Gothic architecture',
    sights: ['Inn peninsula panorama', 'Gothic Town Hall', 'City Museum', 'Inn promenade', 'St. Jakob Parish Church'],
    intro: 'From Wasserburg am Inn to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-kaufbeuren-flughafen-muenchen': {
    description: 'Kaufbeuren is a city in the Allgäu with a fully preserved town wall, known for the Tänzelfest – Bavaria\'s oldest children\'s festival.',
    history: 'Kaufbeuren was a Free Imperial City and prospered through linen weaving. The town wall with its towers is almost fully preserved. The Tänzelfest (since 1497) is Bavaria\'s oldest children\'s festival, held every July.',
    known_for: 'Tänzelfest, town wall, gateway to the Allgäu',
    sights: ['Town wall with Blaserturm', 'Tänzelfest venue (July)', 'City Museum', 'Kaiser-Max-Strasse (old town)', 'Neugablonz (glass jewellery district)'],
    intro: 'From Kaufbeuren to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-marktoberdorf-flughafen-muenchen': {
    description: 'Marktoberdorf is the district town of Ostallgäu and known as the home of AGCO (Fendt tractors) and the International Music Academy.',
    history: 'Marktoberdorf was a residence of the Augsburg prince-bishops and received its town charter in 1488. The International Music Academy Marktoberdorf has been a globally recognised music centre since 1946.',
    known_for: 'Fendt tractors, Music Academy, Ostallgäu',
    sights: ['St. Martin Parish Church', 'Marktoberdorf Residenz', 'Bavarian Railway Museum', 'Fendt tractor factory', 'Allgäuer Festwoche (August)'],
    intro: 'From Marktoberdorf to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-memmingen-flughafen-muenchen': {
    description: 'Memmingen is a former Free Imperial City in western Allgäu with an excellently preserved old town and its own airport (Allgäu Airport).',
    history: 'Memmingen was a significant centre for textile and leather trade as a Free Imperial City. The Twelve Articles of 1525 – a foundational document of the Peasants\' War – were written here. The old town is one of the best preserved in Bavaria.',
    known_for: 'Free Imperial City, Allgäu Airport, Twelve Articles',
    sights: ['Market Square with Steuerhaus', 'Town walls and towers', 'Antonierhaus', 'Allgäu Airport (budget airline hub)', 'City Museum'],
    intro: 'From Memmingen to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-sonthofen-flughafen-muenchen': {
    description: 'Sonthofen is the district town of Oberallgäu and the gateway to the Allgäu Alps – Oberstdorf is only 15 km away.',
    history: 'Sonthofen received its town charter in 1463 and was shaped by timber trade and agriculture. The NS Ordensburg Sonthofen (1934) is now a Bundeswehr site. Its proximity to Oberstdorf and the Allgäu Alps makes Sonthofen a tourism hub.',
    known_for: 'Upper Allgäu centre, Allgäu Alps, close to Oberstdorf',
    sights: ['Staufner Berg (viewpoint)', 'Iller Valley cycling route', 'Burgberger Horn (hiking)', 'Grünten (1,738 m, "Warden of the Allgäu")', 'Oberstdorf (15 km)'],
    intro: 'From Sonthofen to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-neu-ulm-flughafen-muenchen': {
    description: 'Neu-Ulm lies directly opposite Ulm (Baden-Württemberg) on the Bavarian side of the Danube and is known for the Edwin-Scharff Museums.',
    history: 'Neu-Ulm was founded as a Bavarian city in 1810 following the Napoleonic reorganisation. The Fortress of Neu-Ulm (19th century) was part of the federal fortress of Ulm.',
    known_for: 'Danube city, fortress, twin city of Ulm',
    sights: ['Edwin-Scharff Museums', 'Danube riverside promenade', 'Glacis – historic fortress grounds', 'Ulm Minster (across the river in Ulm)', 'EuropaPark proximity'],
    intro: 'From Neu-Ulm to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-donauwörth-flughafen-muenchen': {
    description: 'Donauwörth lies at the confluence of the Danube and Wörnitz, is part of the Romantic Road and known for the Reichsstraße – one of Bavaria\'s most beautiful streets.',
    history: 'Donauwörth was a Free Imperial City and suffered heavy destruction in the Thirty Years\' War. The Reichsstraße with its colourful townhouses is one of Bavaria\'s most impressive old-town streets.',
    known_for: 'Romantic Road, Reichsstraße, Danube-Wörnitz confluence',
    sights: ['Reichsstraße (grand street)', 'Fugger House', 'Holy Cross Church (pilgrimage)', 'Danube cycling route', 'City Museum'],
    intro: 'From Donauwörth to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-dillingen-an-der-donau-flughafen-muenchen': {
    description: 'Dillingen an der Donau is the district town of its eponymous district in Swabia, known as an episcopal residence and 17th/18th-century university city.',
    history: 'Dillingen was the residence of the Augsburg prince-bishops and hosted a significant Jesuit university from 1549. The parish church and palace are magnificent Baroque buildings.',
    known_for: 'Baroque city, Episcopal residence, Danube Swabia',
    sights: ['Dillingen Palace (Baroque façade)', 'St. Peter\'s Parish Church', 'College building (former university)', 'Danube riverside promenade', 'Teutonic Order Palace'],
    intro: 'From Dillingen an der Donau to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-guenzburg-flughafen-muenchen': {
    description: 'Günzburg is the district town of Günzburg district in Swabia and known as the home of LEGOLAND Deutschland Resort – one of Germany\'s most visited theme parks.',
    history: 'Günzburg was a Habsburg residence city and the birthplace of Maria of Austria (consort of Philip II of Spain). LEGOLAND (since 2002) has made the city a family destination. The Frauenkirche (1736–1741) is a key work of Swabian Baroque.',
    known_for: 'LEGOLAND, Baroque church, Maria of Austria',
    sights: ['LEGOLAND Deutschland Resort', 'Frauenkirche Günzburg (Baroque)', 'City Museum', 'Günz cycling route', 'Günzburg Palace (remains)'],
    intro: 'From Günzburg to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-mindelheim-flughafen-muenchen': {
    description: 'Mindelheim is the district town of Unterallgäu and known for its medieval old town, Mindelburg castle and as the birthplace of military commander Georg von Frundsberg.',
    history: 'Mindelheim received its town charter in the 13th century under Georg von Frundsberg, the "Father of the Landsknechts". Mindelburg Castle (12th century) towers over the old town.',
    known_for: 'Georg von Frundsberg, Mindelburg Castle, Unterallgäu',
    sights: ['Mindelburg Castle', 'St. Stephen\'s Parish Church (Jesuit church)', 'Mindelheim City Museum', 'Mindel cycling route', 'Augsburg-Swabia cycling tour'],
    intro: 'From Mindelheim to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-oberstdorf-flughafen-muenchen': {
    description: 'Oberstdorf is Germany\'s southernmost town and a world-famous ski and hiking resort in the Allgäu Alps, host of the Four Hills Tournament.',
    history: 'Oberstdorf developed from a farming village into a tourist destination in the 19th century. The Four Hills Tournament New Year\'s ski jumping (since 1953) brings international fame. The Fellhorn, Nebelhorn and Kleinwalsertal are major ski areas.',
    known_for: 'Four Hills Tournament, Germany\'s southernmost town, Allgäu Alps',
    sights: ['Nebelhorn (2,224 m, cable car)', 'Fellhorn (2,038 m)', 'Breitachklamm gorge (hiking)', 'Four Hills Tournament ski jump', 'Kleinwalsertal (Austria, 5 km)'],
    intro: 'From Oberstdorf to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  // Austria ski resorts
  'taxi-seefeld-in-tirol-flughafen-muenchen': {
    description: 'Seefeld in Tirol is an exclusive Tyrolean spa resort on the Karwendel plateau, host of the Olympic cross-country skiing events in 1964 and 1976.',
    history: 'Seefeld was a hunting ground for the Innsbruck courts and developed into a luxury winter sports resort in the 20th century. The 1964 and 1976 Winter Olympics cross-country events made Seefeld internationally famous.',
    known_for: 'Olympic cross-country skiing, luxury spa resort, Karwendel plateau',
    sights: ['Seekirchl (Baroque church)', 'Seefeld Plateau (cross-country & hiking)', 'Reither Spitze (cable car)', 'Casino Seefeld', 'Wildsee lake'],
    intro: 'From Seefeld in Tirol to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-ellmau-flughafen-muenchen': {
    description: 'Ellmau am Wilden Kaiser is part of the SkiWelt Wilder Kaiser-Brixental – Austria\'s largest ski area with 280 km of runs.',
    history: 'Ellmau was a small Tyrolean farming village that became a popular holiday destination through winter tourism in the 20th century. The Wilder Kaiser, a distinctive rock massif, is the region\'s landmark.',
    known_for: 'SkiWelt Wilder Kaiser, family ski area, Wilder Kaiser',
    sights: ['SkiWelt Wilder Kaiser (280 km of runs)', 'Wilder Kaiser (climbing & hiking)', 'Kaiserbad (wellness pool)', 'Barenbichlalm', 'Going am Wilden Kaiser (neighbouring village)'],
    intro: 'From Ellmau to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-soell-flughafen-muenchen': {
    description: 'Söll is a traditional Tyrolean village at the foot of the Hohe Salve and part of the SkiWelt ski area – known for après-ski and the Hexenkessel atmosphere.',
    history: 'Söll developed into a party village for winter tourism in the 1970s and 80s. The Hexenwasser (children\'s adventure forest) makes it attractive for families today. The Hohe Salve (1,829 m) offers panoramic views of 83 mountain peaks.',
    known_for: 'Hohe Salve, SkiWelt, après-ski, Hexenwasser',
    sights: ['Hohe Salve (1,829 m, gondola)', 'SkiWelt Wilder Kaiser', 'Hexenwasser (adventure forest)', 'Söll village church', 'Après-ski bars'],
    intro: 'From Söll to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-kirchberg-in-tirol-flughafen-muenchen': {
    description: 'Kirchberg in Tirol is part of the Kitzbühel ski area and provides access to the Hahnenkamm gondola – often with more affordable accommodation than Kitzbühel itself.',
    history: 'Kirchberg was a traditional Tyrolean farming village and developed in the second half of the 20th century as a more affordable alternative to Kitzbühel. The Kitzbühel ski area is accessible via connecting lifts.',
    known_for: 'Kitzbühel alternative, Brixental, Tyrolean village',
    sights: ['Kitzbühel/Kirchberg ski area', 'Parish church (Gothic)', 'Brixentalbach promenade', 'Reith bei Kitzbühel (5 km)', 'Bichlalm (hiking)'],
    intro: 'From Kirchberg in Tirol to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-westendorf-flughafen-muenchen': {
    description: 'Westendorf is a charming Tyrolean ski village in the Brixental, part of the SkiWelt ski area and known as an authentic village with excellent value for money.',
    history: 'Westendorf was a small Tyrolean farming village and developed as a tourism destination in the 1970s. The village is part of SkiWelt Wilder Kaiser-Brixental, giving access to 280 km of runs.',
    known_for: 'SkiWelt, Brixental, authentic Tyrolean village',
    sights: ['SkiWelt Brixental (gondola)', 'Talkaser (hiking area)', 'Village square with parish church', 'Kelchsau (quiet side valley)', 'Kitzbüheler Horn (25 km)'],
    intro: 'From Westendorf to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-alpbach-flughafen-muenchen': {
    description: 'Alpbach has been voted Austria\'s most beautiful village several times and is known for the European Forum Alpbach – a renowned science and culture forum.',
    history: 'Alpbach is a mountain village in the Tyrolean lower Inn Valley that became the founding location of the European Forum Alpbach in 1945 – one of the world\'s oldest interdisciplinary forums. The uniform architectural style with flower decorations makes it the most photographed village in Austria.',
    known_for: 'Austria\'s most beautiful village, European Forum, Alpbach Valley',
    sights: ['European Forum Alpbach (August)', 'Alpbachtal Seenland ski area', 'St. Oswald Parish Church', 'Alpbach Valley viewpoint', 'Reither Kogel (hiking)'],
    intro: 'From Alpbach to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-mayrhofen-flughafen-muenchen': {
    description: 'Mayrhofen is the heart of the Zillertal and a world-famous ski and hiking resort – home to Austria\'s steepest piste (Harakiri, 78% gradient).',
    history: 'Mayrhofen developed from a farming village into an international tourist destination in the 20th century. The Penken ski area and the legendary Harakiri run made Mayrhofen world-famous. The Snowbombing Festival (music + skiing) attracts thousands annually.',
    known_for: 'Zillertal, Harakiri run, Snowbombing Festival, après-ski',
    sights: ['Penkenbahn & Harakiri (Austria\'s steepest piste)', 'Ahorn (family mountain)', 'Zillertal Höhenstrasse', 'Mayrhofen leisure pool', 'Snowbombing Festival'],
    intro: 'From Mayrhofen to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-zell-im-zillertal-flughafen-muenchen': {
    description: 'Zell im Zillertal is the main municipality of the Zillertal and the hub of the Zillertalbahn – the famous narrow-gauge railway through the valley.',
    history: 'Zell im Zillertal has a long mining tradition (silver, copper). The Zillertalbahn (since 1902) connects the village with Jenbach and is now a tourist attraction. The Zillertaler Fasching is one of the most famous Tyrolean customs.',
    known_for: 'Zillertalbahn, Gauder Fest, Zillertal centre',
    sights: ['Zillertalbahn (steam and diesel railway)', 'Rosenalm (hiking area)', 'Gauder Fest (spring festival)', 'Assumption Parish Church', 'Kreuzjoch (ski area)'],
    intro: 'From Zell im Zillertal to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-fieberbrunn-flughafen-muenchen': {
    description: 'Fieberbrunn is part of the SkiCircus Saalbach-Hinterglemm-Leogang-Fieberbrunn – one of the largest ski areas in the Alps with 270 km of runs.',
    history: 'Fieberbrunn was a small Pillerseetal village and became part of one of Europe\'s largest ski areas when connected to the Saalbach ski resort in 2015. The Freeride World Tour stop makes Fieberbrunn world-famous among freeride enthusiasts.',
    known_for: 'Freeride World Tour, SkiCircus, Pillerseetal',
    sights: ['SkiCircus Saalbach-Hinterglemm-Fieberbrunn (270 km)', 'Freeride World Tour (January)', 'Pillerseetal (hiking)', 'Buchensteinwand (via ferrata)', 'Pillersee (swimming lake)'],
    intro: 'From Fieberbrunn to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-st-anton-am-arlberg-flughafen-muenchen': {
    description: 'St. Anton am Arlberg is the cradle of alpine skiing and one of the world\'s most prestigious ski resorts – the Arlberg ski area has 305 km of runs.',
    history: 'Hannes Schneider pioneered modern alpine skiing in St. Anton in the early 20th century and opened the world\'s first ski school in 1921. The Arlberg ski area (including Lech, Zürs, Stuben) is considered the finest ski area in the Alps.',
    known_for: 'Birthplace of skiing, Arlberg, Hannes Schneider',
    sights: ['Arlberg ski area (305 km of runs)', 'St. Anton Ski Museum', 'Valluga (2,811 m)', 'Après-ski Mooserwirt & Krazy Kanguruh', 'Arlberg Tunnel'],
    intro: 'From St. Anton am Arlberg to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-lech-am-arlberg-flughafen-muenchen': {
    description: 'Lech am Arlberg is one of the world\'s most exclusive ski resorts, a favourite winter holiday destination for European royal families and the elite.',
    history: 'Lech was settled in the 14th century by Walser people (Alemanni). In the 20th century the village became the meeting place of the rich and famous. The Dutch royal family, numerous aristocrats and prominent guests make Lech the "St. Moritz of Austria".',
    known_for: 'Luxury ski resort, European royal families, White Ring race',
    sights: ['White Ring ski race (January)', 'Arlberg ski area with Zürs', 'Oberlech (car-free village, 1,750 m)', 'Warth-Schröcken ski area', 'Spa hotels & luxury accommodation'],
    intro: 'From Lech am Arlberg to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-soelden-flughafen-muenchen': {
    description: 'Sölden in the Ötztal is known from the James Bond film "Spectre", the Ian Fleming Ice Q restaurant on the Gaislachkogl, and as a top World Cup ski event venue.',
    history: 'Sölden developed into a winter sports destination in the 20th century. The Ski World Cup season opener on the Rettenbachferner glacier (annually in October) makes Sölden the season-starting venue. The Ian Fleming Ice Q (2,174 m) – filming location for "Spectre" – attracts Bond fans from around the world.',
    known_for: 'James Bond Spectre, World Cup season opener, Ötztal glacier',
    sights: ['Gaislachkogl (3,058 m, gondola)', 'Ian Fleming Ice Q (James Bond restaurant)', 'Rettenbachferner glacier', 'Tiefenbachgletscher', 'Aqua Dome Längenfeld (12 km)'],
    intro: 'From Sölden to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-ischgl-flughafen-muenchen': {
    description: 'Ischgl is the "Ibiza of the Alps" – world-famous for spectacular Top-of-the-Mountain concerts, exclusive après-ski and the Silvretta ski area.',
    history: 'Ischgl was a poor mountain farming village until the 1960s. Smuggling over the Fimbapass to Galtur was a source of income. Today Ischgl is one of the world\'s most expensive and glamorous ski resorts. The Top-of-the-Mountain concerts (Elton John, Shakira etc.) are legendary.',
    known_for: 'Ibiza of the Alps, Top-of-the-Mountain concerts, après-ski',
    sights: ['Silvretta ski area (238 km of runs)', 'Top-of-the-Mountain concerts', 'Fimba ski area to Samnaun (Switzerland)', 'Ischgl Alpine wellness', 'Paznauner Thaya (gourmet restaurant)'],
    intro: 'From Ischgl to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-obertauern-flughafen-muenchen': {
    description: 'Obertauern is a pure snow sports resort at 1,740 m in the Radstädter Tauern – known for guaranteed deep snow and the circular lift system (no need to go back).',
    history: 'Obertauern sits on the Tauern Pass and was historically an important mountain crossing. As a purely winter sports resort without farming, it developed exclusively for tourism. The Beatles skied here in 1965, filming parts of "Help!".',
    known_for: 'Snow guarantee, Beatles holiday location, Tauern Pass',
    sights: ['Obertauern ski area (100 km, circular system)', 'Seekarspitze (2,350 m)', 'Schneebett (après-ski)', 'Tauern Spa (30 km, Kaprun)', 'Beatles commemoration'],
    intro: 'From Obertauern to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-bad-gastein-flughafen-muenchen': {
    description: 'Bad Gastein is a historic imperial spa resort in the Gastein Valley with a spectacular townscape (a waterfall running right through the centre) and the Gastein ski area.',
    history: 'Bad Gastein was the meeting place of European aristocracy and emperors from the 19th century onwards – Emperor Franz Joseph took regular cures here. The Gastein Waterfall (150 m) flows spectacularly through the town centre. Gastein healing water (radioactive, radon) is medically recognised.',
    known_for: 'Imperial spa resort, Gastein Waterfall, radon healing water',
    sights: ['Gastein Waterfall (in the town centre)', 'Stubnerkogel (cable car, 2,246 m)', 'Felsentherme Gastein thermal spa', 'Böckstein healing gallery (radon therapy)', 'Gastein ski area (200 km)'],
    intro: 'From Bad Gastein to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-kaprun-flughafen-muenchen': {
    description: 'Kaprun lies at the foot of the Kitzsteinhorn and is known for the monumental high-alpine hydroelectric power station – one of the greatest engineering achievements of the post-war era.',
    history: 'The Kaprun reservoir works (1938–1955) are a monument to post-war reconstruction. 155 workers died during construction. The reservoirs at 2,000 m altitude are now a tourist attraction.',
    known_for: 'Kitzsteinhorn, reservoir power station, year-round ski area',
    sights: ['Kitzsteinhorn glacier ski area', 'Kaprun Power Station (tours)', 'Mooserboden & Wasserfallboden reservoirs', 'Tauern Spa Kaprun', 'Zell am See (5 km)'],
    intro: 'From Kaprun to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-hallstatt-flughafen-muenchen': {
    description: 'Hallstatt is the world\'s most photographed village – a UNESCO World Heritage Site on the Hallstätter See that gave its name to the prehistoric Hallstatt period.',
    history: 'The Hallstatt period (c. 800–400 BC) is named after this location – one of Europe\'s most important prehistoric sites. The salt mine (3,500 years old) is the world\'s oldest. The UNESCO site "Hallstatt-Dachstein/Salzkammergut" covers the entire area.',
    known_for: 'UNESCO, world\'s most photographed village, Hallstatt period, Salzkammergut',
    sights: ['Hallstatt Salt Mine (world\'s oldest)', 'Hallstätter See', 'Hallstatt Skywalk (360° views)', 'Parish church with ossuary', 'UNESCO cultural landscape Salzkammergut'],
    intro: 'From Hallstatt to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-schwaz-flughafen-muenchen': {
    description: 'Schwaz was the second-largest city north of the Alps in the 15th/16th century – enriched by silver and copper mining to become the "Mother of all Mines".',
    history: 'In the 15th century Schwaz was the most important city in the Habsburg Empire after Vienna – the silver from the Schwaz mines financed Habsburg world politics. The mines once produced half of Europe\'s silver.',
    known_for: 'Silver mines, Mother of all Mines, Tyrolean silver city',
    sights: ['Schwaz Silver Mine (tours)', 'Parish Church (largest hall church in Tyrol)', 'Freundsberg Castle', 'Inn riverside promenade', 'Stallerhof Wildlife Park (zoo)'],
    intro: 'From Schwaz to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-hall-in-tirol-flughafen-muenchen': {
    description: 'Hall in Tirol is one of Tyrol\'s best-preserved medieval towns – the former salt city on the Inn with Hasegg Castle and Tyrol\'s oldest mint.',
    history: 'Hall was enriched by the salt trade in the 13th century and was for a time more important than Innsbruck. The Hall Mint (1477) struck the first silver thaler coin – the forerunner of the dollar (Thaler → Dollar).',
    known_for: 'Hall Mint, salt city, medieval old town, origin of the dollar',
    sights: ['Hasegg Castle with Mint Tower', 'Hall Old Town (Town Tower)', 'Collegiate Church', 'Inn riverside promenade', 'Solbad Hall (thermal spa)'],
    intro: 'From Hall in Tirol to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-landeck-flughafen-muenchen': {
    description: 'Landeck is the gateway to the Arlberg and the Ötztal, a hub for skiers heading to St. Anton, Ischgl and Sölden.',
    history: 'Landeck lies at the confluence of the Inn and Sanna rivers. Landeck Castle (13th century) towers above the town. As a transit point Landeck was strategically important – today it is the gateway to some of the world\'s best ski areas.',
    known_for: 'Gateway to the Arlberg, Inn-Sanna junction, Tyrolean castles',
    sights: ['Landeck Castle', 'Inn-Sanna confluence', 'Zams (neighbouring municipality, Kronburg)', 'Pontlatz Bridge (historic)', 'Access to Ötztal & Arlberg'],
    intro: 'From Landeck to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
  'taxi-imst-flughafen-muenchen': {
    description: 'Imst is a Tyrolean district capital known for the Schemenlaufen – one of Europe\'s oldest carnival customs (UNESCO Cultural Heritage), held every four years.',
    history: 'Imst was enriched by the bird trade in the Middle Ages – Imst bird traders travelled all over Europe. The Schemenlaufen (since the 15th century) is a fascinating carnival ritual with colourful masks and costumes. Sigmund Freud spent several summers in Imst.',
    known_for: 'Schemenlaufen (UNESCO), bird trade, Freud holiday location',
    sights: ['Schemenlaufen (every 4 years, carnival)', 'Imst Town Tower', 'Tyrolean summer toboggan run', 'Gurgltal (hiking)', 'Hoch-Imst ski area'],
    intro: 'From Imst to Munich Airport it\'s approx. {km} km. Our taxi covers the route in about {min} minutes.',
  },
};

export default en;
