// City photos from Wikimedia Commons (free licences), picked 1 Oct 2026 — /public/images/cities/<slug>.webp
// (hero/about, 1000 px) and <slug>-sm.webp (cards, 480 px). The credit is shown on the page (licence requirement).

export interface CityImage { artist: string; license: string; source: string }

export const cityImages: Record<string, CityImage> = {
  'taxi-aichach-flughafen-muenchen': { artist: "H.Helmlechner", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Aichach_Rathaus_01.jpg" },
  'taxi-alpbach-flughafen-muenchen': { artist: "RoM1982", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Alpbach_-_Blick_talausw%C3%A4rts_.jpg" },
  'taxi-altoetting-flughafen-muenchen': { artist: "Helmlechner", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Alt%C3%B6tting_Rathaus.jpg" },
  'taxi-augsburg-flughafen-muenchen': { artist: "Diego Delso", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Plaza_del_Ayuntamiento,_Augsburgo,_Alemania,_2021-06-04,_DD_32-34_HDR.jpg" },
  'taxi-bad-gastein-flughafen-muenchen': { artist: "C.Stadler/Bwag", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Bad_Gastein_-_Zentrum.JPG" },
  'taxi-bad-reichenhall-flughafen-muenchen': { artist: "Chrischei bgl", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Lattengebirge.jpg" },
  'taxi-bad-toelz-flughafen-muenchen': { artist: "Kassandro", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:ToelzInnenstadt.jpg" },
  'taxi-basel-flughafen-muenchen': { artist: "Norbert Aepli, Switzerland (User:Noebu)", license: "CC BY 2.5", source: "https://commons.wikimedia.org/wiki/File:Rhine_Rhein_Basel_2006_871.JPG" },
  'taxi-berchtesgaden-flughafen-muenchen': { artist: "Eric Sorenson", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Berchtesgaden1.jpg" },
  'taxi-bern-flughafen-muenchen': { artist: "JoachimKohler-HB", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Aareschwelle_und_Altstadt_mit_Erlacherhof_Bern.jpg" },
  'taxi-bregenz-flughafen-muenchen': { artist: "Feel free to use my photos, but please mention me as the aut", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Bregenz_am_Morgen_vom_Seibel,_B%C3%B6hringer.jpg" },
  'taxi-chur-flughafen-muenchen': { artist: "Adrian Michael", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Chur_Juni_2010.jpg" },
  'taxi-dachau-flughafen-muenchen': { artist: "Erchana", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Schloss_Dachau_Apfelbl%C3%BCte@stadt_dachau_PT.jpg" },
  'taxi-davos-flughafen-muenchen': { artist: "MadGeographer", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Davos2.jpg" },
  'taxi-dillingen-an-der-donau-flughafen-muenchen': { artist: "-wuppertaler", license: "CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:GER_Dillingen_an_der_Donau,_K%C3%B6nigstra%C3%9Fe_005.jpg" },
  'taxi-dingolfing-flughafen-muenchen': { artist: "The original uploader was Sue107 at German Wikipedia.\n\n(Orig", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:ChurchDingolfing.jpg" },
  'taxi-donauwoerth-flughafen-muenchen': { artist: "Flodur63", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Donauw%C3%B6rth_-_Kalvarienberg_-_Donauw%C3%B6rth_v_NO_01.jpg" },
  'taxi-dorfen-flughafen-muenchen': { artist: "AHert", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Blick_auf_Dorfen-01.JPG" },
  'taxi-ebersberg-flughafen-muenchen': { artist: "Rufus46", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Marienplatz_5_Ebersberg-1.jpg" },
  'taxi-eichstaett-flughafen-muenchen': { artist: "Martin Geisler", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Eichst..jpg" },
  'taxi-ellmau-flughafen-muenchen': { artist: "Deborah Sulovsky", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Ellmau_im_Sp%C3%A4tsommer_-_September_2020.jpg" },
  'taxi-erding-flughafen-muenchen': { artist: "Matthias 854 at German Wikipedia", license: "CC BY-SA 2.0 de", source: "https://commons.wikimedia.org/wiki/File:109_0994.JPG" },
  'taxi-fieberbrunn-flughafen-muenchen': { artist: "Jean &amp; Nathalie", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Fieberbrunn_2.jpg" },
  'taxi-freising-flughafen-muenchen': { artist: "Radlmoar", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:Freisinger_Dom.jpg" },
  'taxi-friedrichshafen-flughafen-muenchen': { artist: "Themenmixer auf flickr.com", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Blick_vom_Moleturm_auf_die_Altstadt_von_Friedrichshafen.jpg" },
  'taxi-fuerstenfeldbruck-flughafen-muenchen': { artist: "2015 Michael 2015", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Amperbr%C3%BCcke_und_St._Leonhard_2022-08-21.jpg" },
  'taxi-garching-flughafen-muenchen': { artist: "Rudolph Buch", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Garching_Kirche_St._Katharina.JPG" },
  'taxi-garmisch-partenkirchen-flughafen-muenchen': { artist: "Milei.vencel", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Garmisch_P.jpg" },
  'taxi-gauting-flughafen-muenchen': { artist: "Richard Huber", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Gauting,_Schlo%C3%9F_Fu%C3%9Fberg_2012.jpg" },
  'taxi-germering-flughafen-muenchen': { artist: "K.Baas", license: "CC BY-SA 3.0 de", source: "https://commons.wikimedia.org/wiki/File:Germering-Unterpfaffenhofen_Kath_Kirche_StJakob_Alte_Kirchstr6_001_201409_229.jpg" },
  'taxi-gilching-flughafen-muenchen': { artist: "Cholo Aleman", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Gilching_Ortszentrum.jpg" },
  'taxi-grafing-flughafen-muenchen': { artist: "H.Helmlechner", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Marktplatz_Grafing_02.jpg" },
  'taxi-guenzburg-flughafen-muenchen': { artist: "Immanuel Giel", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Innenstadt_Guenzburg_02.JPG" },
  'taxi-haar-flughafen-muenchen': { artist: "AHert", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Bahnhofstr_7-2_Haar-01.jpg" },
  'taxi-hall-in-tirol-flughafen-muenchen': { artist: "-wuppertaler", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:AUT_Hall_in_Tirol,_Burg_Hasegg_004.jpg" },
  'taxi-hallstatt-flughafen-muenchen': { artist: "C.Stadler/Bwag", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Hallstatt_-_Zentrum_.JPG" },
  'taxi-holzkirchen-flughafen-muenchen': { artist: "Rufus46", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Holzkirchen-Marktplatz_Rathaus-1.jpg" },
  'taxi-imst-flughafen-muenchen': { artist: "Haeferl", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Imst_-_Oberstadt_mit_Pfarrkirche_Mari%C3%A4_Himmelfahrt.jpg" },
  'taxi-ingolstadt-flughafen-muenchen': { artist: "-wuppertaler", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:GER_Ingolstadt_Rathausplatz_013.jpg" },
  'taxi-innsbruck-flughafen-muenchen': { artist: "Nicholas Hartmann", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:2007_Austria_Innsbruck_Inn_river_%26_Altstadt.jpg" },
  'taxi-ischgl-flughafen-muenchen': { artist: "Monika Dittrich", license: "CC BY-SA 3.0 at", source: "https://commons.wikimedia.org/wiki/File:Kirchemathon2.jpg" },
  'taxi-ismaning-flughafen-muenchen': { artist: "Wolkenkratzer", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Schloss_Ismaning_001.jpg" },
  'taxi-kaprun-flughafen-muenchen': { artist: "User:Mateus2019", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:AUT_%E2%80%94_Land_Salzburg_%E2%80%94_Bezirk_Zell_am_See_%E2%80%94_Gemeinde_Kaprun_%E2%80%94_Kitzsteinhorn_(Blick_auf_Zell_am_See_und_Kaprun)_2021.jpeg" },
  'taxi-kaufbeuren-flughafen-muenchen': { artist: "Ulrich Batzer", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Kaufbeurer_Altstadt.jpg" },
  'taxi-kelheim-flughafen-muenchen': { artist: "Michael.chlistalla", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Befreiungshalle-kelheim-aussen2.jpg" },
  'taxi-kempten-flughafen-muenchen': { artist: "Trueman2869", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Ausblick_vom_Mariaberg.jpg" },
  'taxi-kirchberg-in-tirol-flughafen-muenchen': { artist: "Paul David Doherty (User:PDD)", license: "CC BY 2.5", source: "https://commons.wikimedia.org/wiki/File:Kirchberg-in-Tirol.Pfarrkirche.jpg" },
  'taxi-kirchheim-bei-muenchen-flughafen-muenchen': { artist: "MaxM", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Standreaskirchheim.jpg" },
  'taxi-kitzbuehl-flughafen-muenchen': { artist: "Bbb", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:KB_VorderstadtA.jpg" },
  'taxi-konstanz-flughafen-muenchen': { artist: "Wikimedia Commons", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Konstanz_im_Schnee_2006.jpg" },
  'taxi-kufstein-flughafen-muenchen': { artist: "Rufus46", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Kufstein_Festung_Pendling-1.jpg" },
  'taxi-landeck-flughafen-muenchen': { artist: "Asurnipal", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Burg_Landeck_von_Perfuchs.jpg" },
  'taxi-landsberg-am-lech-flughafen-muenchen': { artist: "Zairon", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Landsberg_Lechschnellen_3.JPG" },
  'taxi-landshut-flughafen-muenchen': { artist: "Franzfoto", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Landshut_-_Kirche_St._Martin_14-15._Jh._Sicht_von_der_Burg.jpg" },
  'taxi-lech-am-arlberg-flughafen-muenchen': { artist: "Florian Lindner", license: "CC BY 2.5", source: "https://commons.wikimedia.org/wiki/File:Lech_am_Arlberg_2006.jpg" },
  'taxi-lindau-flughafen-muenchen': { artist: "Ingo2802 at German Wikipedia", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Lindau_Hafeneinfahrt.jpg" },
  'taxi-luzern-flughafen-muenchen': { artist: "W. Bulach", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:00_0055_Buildings_in_Lucerne.jpg" },
  'taxi-marktoberdorf-flughafen-muenchen': { artist: "Flodur63", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:MOD_-_Amtshaus_ehem,_Marktbrunnen.JPG" },
  'taxi-mayrhofen-flughafen-muenchen': { artist: "Wolkenkratzer", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Mayrhofen_006.jpg" },
  'taxi-memmingen-flughafen-muenchen': { artist: "User:Thomas Mirtsch", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Blick_%C3%BCber_Osten_Memmingens_1.jpg" },
  'taxi-miesbach-flughafen-muenchen': { artist: "Rufus46", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Marktplatz_1_Miesbach-1.jpg" },
  'taxi-mindelheim-flughafen-muenchen': { artist: "Diego Delso", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Marienplatz,_Mindelheim,_Alemania,_2019-06-21,_DD_03.jpg" },
  'taxi-muehldorf-am-inn-flughafen-muenchen': { artist: "Alexander Z.", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:MuehldorfOldTown2.jpg" },
  'taxi-muenchen-flughafen-muenchen': { artist: "Thomas Wolf, www.foto-tw.de", license: "CC BY-SA 3.0 de", source: "https://commons.wikimedia.org/wiki/File:Stadtbild_M%C3%BCnchen.jpg" },
  'taxi-murnau-flughafen-muenchen': { artist: "ErwinMeier", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Murnau_Maria-Hilf_02.jpg" },
  'taxi-neu-ulm-flughafen-muenchen': { artist: "-stk", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:202408_aerial_view_of_Neu-Ulm.jpg" },
  'taxi-neuburg-an-der-donau-flughafen-muenchen': { artist: "H.Helmlechner", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Schloss_Neuburg_a.d._Donau_01.jpg" },
  'taxi-nuernberg-flughafen-muenchen': { artist: "Fred Romero from Paris, France", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:N%C3%BCrnberg_-_N%C3%BCrnberger_Burg_(1).jpg" },
  'taxi-oberstdorf-flughafen-muenchen': { artist: "Dirk D.", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Blick_auf_Oberstdorf_im_Allg%C3%A4u.jpg" },
  'taxi-obertauern-flughafen-muenchen': { artist: "Petar Milošević", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Obertauern_Alps.jpg" },
  'taxi-olching-flughafen-muenchen': { artist: "Richard Huber", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Olching,_Amper.jpg" },
  'taxi-passau-flughafen-muenchen': { artist: "Aconcagua", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Passau_Altstadt_Panorama_5.jpg" },
  'taxi-penzberg-flughafen-muenchen': { artist: "Dragemi", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Stadt_Penzberg_im_Oberbayerischen_Landkreis_Weilheim-Schongau.png" },
  'taxi-pfaffenhofen-flughafen-muenchen': { artist: "by Eppasandas", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Pfaffenhofen-Hauptplatz.jpg" },
  'taxi-prien-am-chiemsee-flughafen-muenchen': { artist: "Späth Chr / ChiemseeMan at de.wikipedia", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:PrienKircheMarktplatz.jpg" },
  'taxi-puchheim-flughafen-muenchen': { artist: "Buachamer", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:St_Josef_Kirche_Puchheim-Bahnhof.JPG" },
  'taxi-regensburg-flughafen-muenchen': { artist: "No machine-readable author provided. Grizurgbg assumed (base", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Regensburg_08_2006_2.jpg" },
  'taxi-rosenheim-austria-flughafen-muenchen': { artist: "William Hedington", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Kitzbuhelerhorn.jpg" },
  'taxi-rosenheim-flughafen-muenchen': { artist: "G.Piezinger", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Rosenheim_Hl.-Geist-2010.JPG" },
  'taxi-salzburg-flughafen-muenchen': { artist: "Photo: Andreas Praefcke", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:Salzburg_Altstadt_vom_M%C3%B6nchsberg.jpg" },
  'taxi-schongau-flughafen-muenchen': { artist: "Bbb", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Schongau_Muenzstr.jpg" },
  'taxi-schwaz-flughafen-muenchen': { artist: "Wolfgang H. Wögerer, Wien", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:Schwaz_(Tyrol)_from_NE_closer.jpg" },
  'taxi-seefeld-in-tirol-flughafen-muenchen': { artist: "Robert F. Tobler", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Seefeld_in_Tirol_Austria_from_ESE_on_2014-10-18.png" },
  'taxi-soelden-flughafen-muenchen': { artist: "Leo-setä", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Soelden.jpg" },
  'taxi-soell-flughafen-muenchen': { artist: "Jaap Kievit", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:S%C3%B6ll_southwards_2010.jpg" },
  'taxi-sonthofen-flughafen-muenchen': { artist: "Lokilech", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:SonthofenVonOben.jpg" },
  'taxi-st-anton-am-arlberg-flughafen-muenchen': { artist: "Johnfmh at English Wikipedia", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:STANTON2.jpg" },
  'taxi-st-gallen-flughafen-muenchen': { artist: "Schaffhausen", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Sankt_Gallen.jpg" },
  'taxi-starnberg-flughafen-muenchen': { artist: "Boschfoto", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Starnberg,_HB-06.jpg" },
  'taxi-straubing-flughafen-muenchen': { artist: "Benutzer:Donaulustig", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Straubinger_Stadtbild.jpg" },
  'taxi-taufkirchen-vils-flughafen-muenchen': { artist: "Rottaler", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:08-08-10%2B15-23-44%2BTaufkirchen_(Vils),_Wasserschloss.JPG" },
  'taxi-traunstein-flughafen-muenchen': { artist: "Flodur63", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Surberg,_TS_-_Ettendorfer_Kircherl_-_Traunstein_v_NO_03.jpg" },
  'taxi-tutzing-flughafen-muenchen': { artist: "Wikimedia Commons", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Tutzing01.jpg" },
  'taxi-ulm-flughafen-muenchen': { artist: "Ingo Stoeldt", license: "CC BY 2.5", source: "https://commons.wikimedia.org/wiki/File:Ulm_vom_sprollheim_aus.jpg" },
  'taxi-unterschleissheim-flughafen-muenchen': { artist: "Sacha47", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Rathaus_Unterschlei%C3%9Fheim,_Haupteingang,_22.8.2015_-_2.JPG" },
  'taxi-vaterstetten-flughafen-muenchen': { artist: "Renardo la vulpo", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Vaterstetten,_Rathaus_v_SO,_1.jpeg" },
  'taxi-waldkraiburg-flughafen-muenchen': { artist: "Neustädtler", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Waldkraiburg.JPG" },
  'taxi-wasserburg-am-inn-flughafen-muenchen': { artist: "Carsten Steger", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Aerial_image_of_Wasserburg_am_Inn.jpg" },
  'taxi-weilheim-flughafen-muenchen': { artist: "Oliver Spalt", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Weilheim2.jpg" },
  'taxi-westendorf-flughafen-muenchen': { artist: "www.gpix.at", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Brixental_Panorama.jpg" },
  'taxi-winterthur-flughafen-muenchen': { artist: "Simon Aughton", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:View_of_Winterthur.jpg" },
  'taxi-woergl-flughafen-muenchen': { artist: "Thom16", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Woergl_Westen.JPG" },
  'taxi-wolfratshausen-flughafen-muenchen': { artist: "Ricardalovesmonuments", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Altstadt_Wolfratshausen_vom_Loisach-Ostuferpark.jpg" },
  'taxi-zell-am-see-flughafen-muenchen': { artist: "Andrew Bossi", license: "CC BY-SA 2.5", source: "https://commons.wikimedia.org/wiki/File:1283_-_Zell_am_See.JPG" },
  'taxi-zell-im-zillertal-flughafen-muenchen': { artist: "Haeferl", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Zell_am_Ziller_-_Pfarrkirche_hl_Veit_-_II.jpg" },
  'taxi-zuerich-flughafen-muenchen': { artist: "Ikiwaner", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Zuerich_Fraumuenster_St_Peter.jpg" },
  'taxi-allershausen-flughafen-muenchen': { artist: "Didi43", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Allershausen,_Pfarrkirche_St.Josef.jpg" },
  'taxi-aschheim-flughafen-muenchen': { artist: "Bayreuth2009", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:Aschheim,_kath._St.Peter_und_Paul-Kirche_(02).jpg" },
  'taxi-au-in-der-hallertau-flughafen-muenchen': { artist: "H.Helmlechner", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Au_in_der_Hallertau_Ortsansicht.jpg" },
  'taxi-eching-flughafen-muenchen': { artist: "Dguendel", license: "CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:Eching_(Landkreis_Freising),_das_Rathaus.jpg" },
  'taxi-eitting-flughafen-muenchen': { artist: "Brücke-Osteuropa", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Eitting_2.JPG" },
  'taxi-feldkirchen-flughafen-muenchen': { artist: "Comcos", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Feldkirchen_Church_1837_south.jpg" },
  'taxi-finsing-flughafen-muenchen': { artist: "Mosiva", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Rathaus-Finsing.jpg" },
  'taxi-haimhausen-flughafen-muenchen': { artist: "Gras-Ober", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Schloss_Haimhausen_2.jpg" },
  'taxi-hallbergmoos-flughafen-muenchen': { artist: "Dr. Bernd Gross", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Hallbergmoos.JPG" },
  'taxi-karlsfeld-flughafen-muenchen': { artist: "Wzwz", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Wohngebiet_in_Karlsfeld.jpg" },
  'taxi-kranzberg-flughafen-muenchen': { artist: "MaxM", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Fischerwirt_kranzberg.jpg" },
  'taxi-mainburg-flughafen-muenchen': { artist: "H. Helmlechner", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Mainburg_Zentrum_01.jpg" },
  'taxi-markt-schwaben-flughafen-muenchen': { artist: "user:J. Patrick Fischer", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:MS-Kirche2.JPG" },
  'taxi-marzling-flughafen-muenchen': { artist: "Vuxi", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Marzling.JPG" },
  'taxi-moosburg-flughafen-muenchen': { artist: "Björn Laczay from Moosburg, Germany", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Auf_dem_Gries.jpg" },
  'taxi-neubiberg-flughafen-muenchen': { artist: "Rufus46", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Neubiberg_Rathaus-1.jpg" },
  'taxi-neufahrn-flughafen-muenchen': { artist: "Dr. Bernd Gross", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Neufahrn_bei_Freising.JPG" },
  'taxi-oberding-flughafen-muenchen': { artist: "Bjs", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Oberding-bjs100404-01.jpg" },
  'taxi-oberschleissheim-flughafen-muenchen': { artist: "Carsten Steger", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Aerial_image_of_the_Schleissheim_Palace.jpg" },
  'taxi-ottobrunn-flughafen-muenchen': { artist: "LepoRello", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Ottobrunn_St._Otto_von_Osten.jpg" },
  'taxi-pliening-flughafen-muenchen': { artist: "AHert", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Rathaus_Pliening-01.JPG" },
  'taxi-poing-flughafen-muenchen': { artist: "Gemeinde Poing", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Poing-blick-ueber-neubaugebiet.jpg" },
  'taxi-taufkirchen-bei-muenchen-flughafen-muenchen': { artist: "2015 Michael 2015", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:St._Johannes_der_T%C3%A4ufer_(Taufkirchen),_2023-02-26.jpg" },
  'taxi-unterfoehring-flughafen-muenchen': { artist: "Bayreuth2009", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:Unterf%C3%B6hring,_kath._St.Valentin-Kirche,_Feldkirchen_(01).jpg" },
  'taxi-unterhaching-flughafen-muenchen': { artist: "MyName (Gamsbart)", license: "CC BY 3.0 de", source: "https://commons.wikimedia.org/wiki/File:Unterhaching_-_Rathaus.JPG" },
  'taxi-wartenberg-flughafen-muenchen': { artist: "H.Helmlechner", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Wartenberg_Mari%C3%A4_Geburt.jpg" },
};
